export const CATEGORIES_TREE: Record<string, string[]> = {
  "Veículos e Peças": [
    "Motor completo",
    "Bloco de motor",
    "Cabeçote",
    "Junta de motor",
    "Biela",
    "Pistão",
    "Anéis de pistão",
    "Bomba de óleo",
    "Bomba d'água",
    "Correia dentada",
    "Corrente de comando",
    "Tensionador",
    "Vela de ignição",
    "Bobina de ignição",
    "Cabo de vela",
    "Bico injetor",
    "Filtro de ar",
    "Filtro de óleo",
    "Filtro de combustível",
    "Filtro de cabine",
    "Radiador",
    "Intercooler",
    "Mangueira de radiador",
    "Reservatório de água",
    "Alternador",
    "Motor de partida",
    "Bateria automotiva",
    "Cabo de bateria",
    "Central eletrônica",
    "Sensor de rotação",
    "Sensor de temperatura",
    "Sensor MAP",
    "Sonda lambda",
    "Amortecedor dianteiro",
    "Amortecedor traseiro",
    "Mola de suspensão",
    "Coxim de motor",
    "Bandeja",
    "Pivô de suspensão",
    "Barra estabilizadora",
    "Bucha de suspensão",
    "Terminal de direção",
    "Caixa de direção",
    "Bomba de direção hidráulica",
    "Disco de freio",
    "Pastilha de freio",
    "Lona de freio",
    "Cilindro mestre",
    "Servo freio",
    "Pinça de freio",
    "Kit embreagem",
    "Volante do motor",
    "Câmbio manual",
    "Câmbio automático",
    "Junta homocinética",
    "Semi-eixo",
    "Rolamento de roda",
    "Genérica",
  ],
  "Construção, Ferramentas e Elétrica": [
    "Cimento CP II",
    "Cimento CP V",
    "Cimento branco",
    "Cal hidratada",
    "Areia média",
    "Areia fina",
    "Brita 0",
    "Brita 1",
    "Brita 2",
    "Pedrisco",
    "Argamassa colante ACI",
    "Argamassa colante ACII",
    "Argamassa colante ACIII",
    "Rejunte",
    "Rejunte epóxi",
    "Gesso em pó",
    "Placa de gesso acartonado",
    "Perfil metálico Drywall",
    "Massa corrida PVA",
    "Massa acrílica",
    "Selador acrílico",
    "Fundo preparador",
    "Impermeabilizante de parede",
    "Manta asfáltica",
    "Neutrol",
    "Tijolo cerâmico",
    "Tijolo baiano",
    "Tijolo laminado",
    "Bloco de concreto",
    "Bloco estrutural",
    "Telha cerâmica",
    "Telha de fibrocimento",
    "Telha metálica",
    "Telha translúcida",
    "Telha sanduíche",
    "Piso cerâmico",
    "Porcelanato",
    "Piso laminado",
    "Piso vinílico",
    "Deck de madeira",
    "Revestimento 3D",
    "Rodapé",
    "Soleira de granito",
    "Peitoril",
    "Bancada de granito",
    "Bancada de mármore",
    "Vergalhão CA-50",
    "Vergalhão CA-60",
    "Tela soldada",
    "Estribo",
    "Arame recozido",
    "Prego 17x21",
    "Prego 22x48",
    "Parafuso autobrocante",
    "Parafuso para madeira",
    "Parafuso para drywall",
    "Bucha de nylon",
    "Genérica",
  ],
  "Casa, Móveis e Decoração": [
    "Sofá 2 lugares",
    "Sofá 3 lugares",
    "Sofá retrátil",
    "Sofá de canto",
    "Sofá-cama",
    "Poltrona reclinável",
    "Poltrona decorativa",
    "Puff quadrado",
    "Puff redondo",
    "Chaise longue",
    "Rack para TV",
    "Painel para TV",
    "Home theater",
    "Estante para sala",
    "Aparador",
    "Mesa de centro",
    "Mesa lateral",
    "Mesa de jantar 4 lugares",
    "Mesa de jantar 6 lugares",
    "Mesa de jantar 8 lugares",
    "Cadeira de jantar",
    "Buffet",
    "Cristaleira",
    "Bar em madeira",
    "Adega climatizada",
    "Cama box solteiro",
    "Cama box casal",
    "Cama box queen",
    "Cama box king",
    "Colchão solteiro",
    "Colchão casal",
    "Colchão queen",
    "Colchão king",
    "Cabeceira estofada",
    "Criado-mudo",
    "Cômoda",
    "Guarda-roupa 4 portas",
    "Guarda-roupa 6 portas",
    "Guarda-roupa modulado",
    "Sapateira",
    "Cabideiro",
    "Baú organizador",
    "Berço",
    "Cômoda infantil",
    "Guarda-roupa infantil",
    "Escrivaninha infantil",
    "Bicama",
    "Escrivaninha",
    "Cadeira de escritório",
    "Cadeira gamer",
    "Estante para escritório",
    "Arquivo de aço",
    "Armário de cozinha",
    "Balcão de cozinha",
    "Torre quente",
    "Paneleiro",
    "Mesa de canto para cozinha",
    "Genérica",
  ],
  "Eletrodomésticos": [
    "Geladeira 1 porta",
    "Geladeira 2 portas",
    "Geladeira 3 portas",
    "Geladeira French Door",
    "Geladeira frost free",
    "Geladeira duplex",
    "Freezer horizontal",
    "Freezer vertical",
    "Freezer conjugado",
    "Cervejeira",
    "Adega de vinhos",
    "Fogão 4 bocas",
    "Fogão 5 bocas",
    "Fogão 6 bocas",
    "Fogão de piso",
    "Fogão de embutir",
    "Cooktop a gás 4 bocas",
    "Cooktop elétrico",
    "Cooktop de indução",
    "Forno elétrico de embutir",
    "Forno elétrico de bancada",
    "Forno a gás",
    "Micro-ondas 20L",
    "Micro-ondas 30L",
    "Micro-ondas de embutir",
    "Lava-louças 8 serviços",
    "Lava-louças 14 serviços",
    "Máquina de lavar 8kg",
    "Máquina de lavar 12kg",
    "Máquina de lavar 15kg",
    "Máquina de lavar 17kg",
    "Lava e seca",
    "Secadora de roupas",
    "Tanquinho",
    "Refrigerador comercial",
    "Chapa lanchonete",
    "Fritadeira industrial",
    "Liquidificador industrial",
    "Batedeira planetária",
    "Ar-condicionado janela",
    "Ar-condicionado split 7000 BTUs",
    "Ar-condicionado split 9000 BTUs",
    "Ar-condicionado split 12000 BTUs",
    "Ar-condicionado split 18000 BTUs",
    "Ar-condicionado split 24000 BTUs",
    "Ar-condicionado inverter",
    "Ar-condicionado portátil",
    "Climatizador de ar",
    "Ventilador de coluna",
    "Ventilador de mesa",
    "Ventilador de parede",
    "Ventilador de teto",
    "Circulador de ar",
    "Umidificador de ar",
    "Desumidificador",
    "Purificador de ar",
    "Purificador de água",
    "Genérica",
  ],
  "Celulares e Smartphones": [
    "iPhone 15 Pro Max",
    "iPhone 15 Pro",
    "iPhone 15",
    "iPhone 14",
    "iPhone 13",
    "iPhone 12",
    "iPhone SE",
    "Samsung Galaxy S24 Ultra",
    "Samsung Galaxy S24",
    "Samsung Galaxy S23",
    "Samsung Galaxy A54",
    "Samsung Galaxy A34",
    "Samsung Galaxy A14",
    "Samsung Galaxy M54",
    "Motorola Edge 40",
    "Motorola Moto G84",
    "Motorola Moto G73",
    "Motorola Moto G54",
    "Motorola Moto G32",
    "Motorola Moto E13",
    "Xiaomi Redmi Note 13 Pro",
    "Xiaomi Redmi Note 13",
    "Xiaomi Redmi 12",
    "Xiaomi Poco X6",
    "Xiaomi Mi 13",
    "Realme C55",
    "Realme 10",
    "Asus ROG Phone 7",
    "Asus Zenfone 10",
    "Google Pixel 8",
    "Google Pixel 7a",
    "Nokia G22",
    "OnePlus 12",
    "Celular básico dual chip",
    "Celular sênior teclas grandes",
    "Celular infantil",
    "Celular rugged",
    "Feature phone",
    "Capa de silicone",
    "Capa antichoque",
    "Capa flip",
    "Capinha personalizada",
    "Capa transparente",
    "Capa carteira",
    "Película de vidro",
    "Película de hidrogel",
    "Película privativa",
    "Película 3D",
    "Skin adesiva",
    "Carregador de parede USB-C",
    "Carregador de parede Lightning",
    "Carregador Turbo Power",
    "Carregador wireless",
    "Carregador veicular",
    "Cabo USB-C",
    "Cabo Lightning",
    "Cabo micro USB",
    "Genérica",
  ],
  "Informática": [
    "Notebook 14 polegadas",
    "Notebook 15 polegadas",
    "Notebook Ultrafino",
    "Notebook gamer",
    "Notebook 2 em 1",
    "Notebook para estudante",
    "Chromebook",
    "MacBook Air",
    "MacBook Pro",
    "Desktop completo",
    "Desktop gamer",
    "Mini PC",
    "All-in-one",
    "PC para escritório",
    "Placa-mãe ATX",
    "Placa-mãe micro ATX",
    "Placa-mãe ITX",
    "Processador Intel i3",
    "Processador Intel i5",
    "Processador Intel i7",
    "Processador Intel i9",
    "Processador AMD Ryzen 3",
    "Processador AMD Ryzen 5",
    "Processador AMD Ryzen 7",
    "Processador AMD Ryzen 9",
    "Cooler para processador",
    "Water cooler",
    "Memória RAM DDR4 8GB",
    "Memória RAM DDR4 16GB",
    "Memória RAM DDR5 16GB",
    "Memória RAM DDR5 32GB",
    "Memória para notebook",
    "SSD SATA 240GB",
    "SSD SATA 480GB",
    "SSD SATA 1TB",
    "SSD NVMe 500GB",
    "SSD NVMe 1TB",
    "SSD NVMe 2TB",
    "HD 1TB",
    "HD 2TB",
    "HD 4TB",
    "HD externo 1TB",
    "HD externo 2TB",
    "Placa de vídeo GTX 1650",
    "Placa de vídeo RTX 3060",
    "Placa de vídeo RTX 4060",
    "Placa de vídeo RTX 4070",
    "Placa de vídeo Radeon",
    "Placa de rede",
    "Placa de captura",
    "Gabinete ATX",
    "Gabinete gamer",
    "Fonte 500W",
    "Fonte 650W",
    "Fonte 750W",
    "Fonte modular",
    "Genérica",
  ],
  "Eletrônicos, TV e Áudio": [
    "Smart TV 32''",
    "Smart TV 43''",
    "Smart TV 50''",
    "Smart TV 55''",
    "Smart TV 65''",
    "Smart TV 75''",
    "Smart TV 85''",
    "TV OLED",
    "TV QLED",
    "TV 4K UHD",
    "TV 8K",
    "TV com Google TV",
    "TV com Roku",
    "TV com Android TV",
    "Suporte de parede para TV",
    "Suporte articulado para TV",
    "Suporte de teto para TV",
    "Rack giratório para TV",
    "Soundbar 2.0",
    "Soundbar 2.1",
    "Soundbar 5.1",
    "Soundbar Dolby Atmos",
    "Home theater 5.1",
    "Home theater 7.1",
    "Sistema de som Hi-Fi",
    "Caixa de som Bluetooth",
    "Caixa de som portátil",
    "Caixa acústica",
    "Caixa amplificada",
    "Sistema de som para festa",
    "Mini system",
    "Fone de ouvido over-ear",
    "Fone in-ear com fio",
    "Fone Bluetooth com cancelamento de ruído",
    "Fone true wireless",
    "Fone gamer",
    "Microfone lapela",
    "Microfone shotgun",
    "Microfone dinâmico",
    "Microfone condensador",
    "Kit podcast",
    "Receiver AV",
    "Amplificador de som",
    "Mesa de som",
    "Interface de áudio",
    "Placa de som USB",
    "Chromecast",
    "Amazon Fire TV Stick",
    "Apple TV",
    "Roku Express",
    "Box Android TV",
    "Antena digital interna",
    "Antena digital externa",
    "Splitter de antena",
    "Rádio portátil",
    "Rádio relógio",
    "Genérica",
  ],
  "Games": [
    "PlayStation 5",
    "PlayStation 5 Slim",
    "PlayStation 4 Slim",
    "PlayStation 4 Pro",
    "PSP",
    "PS Vita",
    "Xbox Series X",
    "Xbox Series S",
    "Xbox One S",
    "Xbox One X",
    "Xbox 360",
    "Nintendo Switch",
    "Nintendo Switch OLED",
    "Nintendo Switch Lite",
    "Nintendo 3DS",
    "Game Boy Advance",
    "PC gamer completo",
    "Console retrô",
    "Fliperama caseiro",
    "Máquina arcade",
    "Controle DualSense PS5",
    "Controle DualShock PS4",
    "Controle Xbox Series",
    "Controle Xbox One",
    "Controle Joy-Con",
    "Pro Controller Nintendo",
    "Controle arcade",
    "Volante para console",
    "Volante para PC",
    "Pedaleira",
    "Câmbio para volante",
    "Manche joystick",
    "Manche HOTAS",
    "Headset gamer PS5",
    "Headset gamer Xbox",
    "Headset gamer PC",
    "Mesa gamer",
    "Jogo PS5 FIFA",
    "Jogo PS5 EA Sports FC",
    "Jogo PS5 Call of Duty",
    "Jogo PS5 God of War",
    "Jogo PS5 Spider-Man",
    "Jogo Xbox Halo",
    "Jogo Xbox Forza",
    "Jogo Xbox Starfield",
    "Jogo Switch Zelda",
    "Jogo Switch Mario",
    "Jogo Switch Pokémon",
    "Jogo PC Steam",
    "Cartão pré-pago PlayStation",
    "Cartão pré-pago Xbox",
    "Cartão pré-pago Nintendo",
    "Xbox Game Pass",
    "PS Plus",
    "Nintendo Switch Online",
    "Base carregadora para controle",
    "Genérica",
  ],
  "Câmeras e Fotografia": [
    "Câmera DSLR Canon",
    "Câmera DSLR Nikon",
    "Câmera mirrorless Sony",
    "Câmera mirrorless Fujifilm",
    "Câmera mirrorless Canon",
    "Câmera compacta",
    "Câmera instantânea Instax",
    "Câmera analógica",
    "Câmera de ação GoPro",
    "Câmera de ação Insta360",
    "Câmera 360",
    "Drone com câmera",
    "Drone profissional",
    "Drone DJI Mini",
    "Drone racing",
    "Drone agrícola",
    "Lente 18-55mm",
    "Lente 50mm f/1.8",
    "Lente 24-70mm",
    "Lente 70-200mm",
    "Lente grande angular",
    "Lente macro",
    "Lente teleobjetiva",
    "Lente fisheye",
    "Filtro UV",
    "Filtro polarizador",
    "Filtro ND",
    "Filtro colorido",
    "Adaptador de lente",
    "Tripé profissional",
    "Tripé de viagem",
    "Monopé",
    "Cabeça fluida",
    "Estabilizador gimbal",
    "Slider para câmera",
    "Grua de câmera",
    "Iluminador de LED",
    "Softbox",
    "Refletor rebatedor",
    "Fundo infinito",
    "Fundo croma key",
    "Fundo fotográfico",
    "Flash speedlight",
    "Flash de estúdio",
    "Rádio flash",
    "Difusor de flash",
    "Snoot",
    "Grid para flash",
    "Cartão SD 64GB",
    "Cartão SD 128GB",
    "Cartão SD 256GB",
    "Cartão CFexpress",
    "Leitor de cartão fotográfico",
    "HD externo para fotógrafo",
    "SSD portátil",
    "Bolsa para câmera",
    "Genérica",
  ],
  "Moda Feminina": [
    "Blusa manga curta",
    "Blusa manga longa",
    "Camiseta básica feminina",
    "Camisa social feminina",
    "Camisa xadrez feminina",
    "Regata feminina",
    "Cropped",
    "Body feminino",
    "Top ribana",
    "Blusa gola alta",
    "Blusa ombro a ombro",
    "Túnica",
    "Vestido curto",
    "Vestido longo",
    "Vestido midi",
    "Vestido de festa",
    "Vestido de noiva",
    "Vestido de casamento civil",
    "Vestido de festa junina",
    "Vestido plus size",
    "Saia curta",
    "Saia midi",
    "Saia longa",
    "Saia plissada",
    "Saia jeans",
    "Saia lápis",
    "Short saia",
    "Short jeans",
    "Short cintura alta",
    "Short alfaiataria",
    "Short esportivo",
    "Bermuda ciclista",
    "Pijama short",
    "Calça jeans skinny",
    "Calça jeans flare",
    "Calça jeans reta",
    "Calça pantalona",
    "Calça de alfaiataria",
    "Calça jogger feminina",
    "Calça legging",
    "Calça capri",
    "Calça cargo feminina",
    "Calça de moletom",
    "Calça pantacourt",
    "Casaco de lã",
    "Casaco de couro",
    "Sobretudo",
    "Trench coat",
    "Jaqueta jeans",
    "Jaqueta corta-vento",
    "Jaqueta puffer",
    "Blazer feminino",
    "Colete feminino",
    "Cardigã",
    "Kimono",
    "Conjunto feminino",
    "Genérica",
  ],
  "Moda Masculina": [
    "Camiseta básica masculina",
    "Camiseta estampada",
    "Camiseta polo",
    "Camisa manga longa",
    "Camisa xadrez masculina",
    "Camisa social masculina",
    "Camisa slim fit",
    "Camisa jeans",
    "Camisa de linho",
    "Camisa gola padre",
    "Regata masculina",
    "Regata cavada",
    "Camisa térmica",
    "Camisa dry fit",
    "Camisa flanela",
    "Bermuda tactel",
    "Bermuda jeans",
    "Bermuda cargo",
    "Bermuda alfaiataria",
    "Bermuda de banho",
    "Bermuda esportiva",
    "Short esportivo masculino",
    "Calça jeans masculina skinny",
    "Calça jeans masculina reta",
    "Calça jeans masculina slim",
    "Calça alfaiataria masculina",
    "Calça social",
    "Calça cargo masculina",
    "Calça jogger masculina",
    "Calça de moletom masculina",
    "Calça esportiva",
    "Jaqueta corta-vento masculina",
    "Jaqueta jeans masculina",
    "Jaqueta de couro",
    "Jaqueta puffer masculina",
    "Blusa de moletom",
    "Casaco de lã masculino",
    "Sobretudo masculino",
    "Blazer masculino",
    "Colete masculino",
    "Terno completo",
    "Terno slim",
    "Smoking",
    "Colete de terno",
    "Fraque",
    "Casaca",
    "Gravata",
    "Gravata borboleta",
    "Suspensório",
    "Lenço de bolso",
    "Abotoadura",
    "Cueca boxer",
    "Cueca slip",
    "Cueca sunga",
    "Kit cueca",
    "Meia esportiva masculina",
    "Genérica",
  ],
  "Moda Infantil": [
    "Body para bebê",
    "Macacão de bebê",
    "Mijão",
    "Conjunto bebê menino",
    "Conjunto bebê menina",
    "Vestido bebê",
    "Saída maternidade menino",
    "Saída maternidade menina",
    "Camiseta infantil",
    "Camiseta manga longa infantil",
    "Regata infantil",
    "Blusa infantil",
    "Camisa polo infantil",
    "Camisa social infantil",
    "Vestido infantil",
    "Vestido de festa infantil",
    "Vestido para daminha",
    "Saia infantil",
    "Short saia infantil",
    "Bermuda infantil",
    "Short infantil",
    "Calça jeans infantil",
    "Calça de moletom infantil",
    "Calça alfaiataria infantil",
    "Calça legging infantil",
    "Calça cargo infantil",
    "Jaqueta infantil",
    "Casaco infantil",
    "Blazer infantil",
    "Colete infantil",
    "Sobretudo infantil",
    "Cardigã infantil",
    "Moletom infantil",
    "Suéter infantil",
    "Pijama infantil",
    "Pijama para bebê",
    "Camisola infantil",
    "Robe infantil",
    "Sunga infantil",
    "Bermuda praia infantil",
    "Biquíni infantil",
    "Maiô infantil",
    "Camiseta UV infantil",
    "Saída de praia infantil",
    "Canga infantil",
    "Roupa de festa junina infantil",
    "Vestido junino infantil",
    "Camisa xadrez infantil junina",
    "Uniforme escolar infantil",
    "Camiseta escolar",
    "Bermuda escolar",
    "Calça escolar",
    "Blusa escolar",
    "Roupa fitness infantil",
    "Legging infantil fitness",
    "Camiseta esportiva infantil",
    "Genérica",
  ],
  "Calçados": [
    "Tênis casual feminino",
    "Tênis casual masculino",
    "Tênis esportivo feminino",
    "Tênis esportivo masculino",
    "Tênis running",
    "Tênis basquete",
    "Tênis tenistas",
    "Tênis skate",
    "Tênis futsal",
    "Tênis society",
    "Tênis crossfit",
    "Tênis para caminhada",
    "Chuteira campo",
    "Chuteira society",
    "Chuteira futsal",
    "Chuteira baby",
    "Chuteira profissional",
    "Chuteira infantil",
    "Sandália feminina",
    "Sandália rasteirinha",
    "Sandália salto alto",
    "Sandália salto médio",
    "Sandália de amarrar",
    "Sandália gladiadora",
    "Sandália ortopédica",
    "Sandália masculina",
    "Sandália franciscana masculina",
    "Papete",
    "Papete infantil",
    "Sapatilha feminina",
    "Sapatilha bico fino",
    "Sapatilha bailarina",
    "Sapato boneca",
    "Sapato Oxford feminino",
    "Sapato social masculino",
    "Sapato Oxford masculino",
    "Sapato Derby",
    "Sapato mocassim",
    "Sapato brogue",
    "Sapato bico fino",
    "Sapato bico redondo",
    "Bota feminina",
    "Bota masculina",
    "Bota de couro",
    "Bota cano longo",
    "Bota cano curto",
    "Bota over the knee",
    "Bota chelsea",
    "Bota coturno",
    "Bota militar",
    "Bota de trabalho",
    "Bota country",
    "Bota texana feminina",
    "Bota texana masculina",
    "Bota tratorada",
    "Scarpin",
    "Genérica",
  ],
  "Bolsas, Mochilas e Malas": [
    "Bolsa feminina de couro",
    "Bolsa transversal feminina",
    "Bolsa saco",
    "Bolsa hobo",
    "Bolsa tote",
    "Bolsa clutch",
    "Bolsa carteira",
    "Bolsa de festa",
    "Bolsa mini",
    "Bolsa em couro legítimo",
    "Bolsa croco",
    "Bolsa em palha",
    "Bolsa em crochê",
    "Bolsa térmica",
    "Bolsa para academia",
    "Bolsa esportiva",
    "Bolsa duffel",
    "Sacola ecológica",
    "Sacola de compras",
    "Sacola dobrável",
    "Mochila escolar infantil",
    "Mochila escolar juvenil",
    "Mochila com rodinhas",
    "Mochila casual",
    "Mochila feminina",
    "Mochila masculina",
    "Mochila para notebook",
    "Mochila antifurto",
    "Mochila de couro",
    "Mochila tática",
    "Mochila militar",
    "Mochila cargueira",
    "Mochila trilha",
    "Mochila para viagem",
    "Mochila para câmera",
    "Mochila para drone",
    "Mochila para instrumentos musicais",
    "Pochete",
    "Pochete transversal",
    "Bum bag",
    "Necessaire",
    "Estojo escolar",
    "Estojo de maquiagem",
    "Estojo para fone",
    "Mala de viagem P",
    "Mala de viagem M",
    "Mala de viagem G",
    "Mala de bordo",
    "Kit de malas",
    "Mala executiva",
    "Mala de rodinhas",
    "Mala de mão",
    "Mala rígida ABS",
    "Mala rígida policarbonato",
    "Mala flexível",
    "Bolsa de médico",
    "Genérica",
  ],
  "Joias, Relógios e Acessórios": [
    "Anel de ouro",
    "Anel de prata",
    "Anel folheado",
    "Anel solitário",
    "Aliança de casamento",
    "Aliança de compromisso",
    "Anel de formatura",
    "Colar de ouro",
    "Colar de prata",
    "Colar folheado",
    "Colar com pingente",
    "Gargantilha",
    "Choker",
    "Colar longo",
    "Brinco de argola",
    "Brinco de gota",
    "Brinco de pressão",
    "Brinco tarraxa",
    "Brinco pérola",
    "Brinco cravejado",
    "Brinco de zircônia",
    "Brinco ear cuff",
    "Pulseira de ouro",
    "Pulseira de prata",
    "Pulseira folheada",
    "Pulseira riviera",
    "Pulseira em elos",
    "Pulseira com pingente",
    "Pulseira de couro",
    "Bracelete rígido",
    "Pulseira feminina",
    "Pulseira masculina",
    "Tornozeleira feminina",
    "Tornozeleira infantil",
    "Piercing helix",
    "Piercing tragus",
    "Piercing conch",
    "Piercing nariz",
    "Piercing umbigo",
    "Piercing labial",
    "Piercing língua",
    "Corrente masculina cordão",
    "Corrente masculina cadeado",
    "Corrente masculina groumet",
    "Pingente crucifixo",
    "Pingente Nossa Senhora",
    "Pingente estrela de Davi",
    "Medalha de ouro",
    "Medalha de prata",
    "Relógio masculino analógico",
    "Relógio masculino digital",
    "Relógio masculino automático",
    "Relógio masculino cronógrafo",
    "Relógio masculino esportivo",
    "Relógio masculino social",
    "Relógio masculino luxo",
    "Genérica",
  ],
  "Beleza e Perfumaria": [
    "Perfume feminino importado",
    "Perfume masculino importado",
    "Perfume nacional feminino",
    "Perfume nacional masculino",
    "Perfume infantil",
    "Perfume unissex",
    "Deo colônia feminina",
    "Deo colônia masculina",
    "Batom líquido matte",
    "Batom cremoso",
    "Batom hidratante",
    "Gloss labial",
    "Lip tint",
    "Lápis labial",
    "Bálsamo labial",
    "Base líquida",
    "Base em pó",
    "Base bastão",
    "BB cream",
    "CC cream",
    "Corretivo líquido",
    "Corretivo em pau",
    "Primer facial",
    "Fixador de maquiagem",
    "Iluminador",
    "Blush",
    "Bronzer",
    "Contorno facial",
    "Paleta de sombras",
    "Sombra individual",
    "Delineador líquido",
    "Delineador em gel",
    "Delineador em caneta",
    "Lápis de olho",
    "Rímel",
    "Cílios postiços",
    "Cola para cílios",
    "Lash lift",
    "Pó compacto",
    "Pó solto",
    "Pó bronzeador",
    "Kit maquiagem",
    "Case de maquiagem",
    "Pincéis de maquiagem",
    "Esponja de maquiagem",
    "Máscara facial",
    "Sabonete facial",
    "Tônico facial",
    "Sérum facial",
    "Hidratante facial",
    "Protetor solar facial",
    "Protetor solar corporal",
    "Autobronzeador",
    "Óleo corporal",
    "Creme antissinais",
    "Creme para olhos",
    "Genérica",
  ],
  "Saúde e Bem-Estar": [
    "Suplemento whey protein",
    "Creatina",
    "BCAA",
    "Glutamina",
    "Cafeína",
    "Multivitamínico",
    "Vitamina C",
    "Vitamina D",
    "Vitamina B12",
    "Complexo B",
    "Ômega 3",
    "Ômega 6",
    "Colágeno hidrolisado",
    "Colágeno tipo 2",
    "Termogênico",
    "Pré-treino",
    "Hipercalórico",
    "Barra proteica",
    "Whey isolado",
    "Whey concentrado",
    "Albumina",
    "Caseína",
    "Proteína vegana",
    "Proteína de arroz",
    "Proteína de ervilha",
    "Whey vegano",
    "Ferro suplemento",
    "Zinco",
    "Magnésio",
    "Cálcio",
    "Potássio",
    "Cromo",
    "Selênio",
    "Cúrcuma",
    "Óleo de coco",
    "Chia",
    "Linhaça",
    "Psyllium",
    "Spirulina",
    "Chlorella",
    "Espinheira santa",
    "Ginkgo biloba",
    "Ginseng",
    "Adaptógenos",
    "Melatonina",
    "Triptofano",
    "Valeriana",
    "Passiflora",
    "Camomila",
    "Erva-cidreira",
    "Chá verde",
    "Chá branco",
    "Chá preto",
    "Chá de hibisco",
    "Chá matcha",
    "Chá mate",
    "Genérica",
  ],
  "Farmácia e Cuidados Pessoais": [
    "Analgésico dipirona",
    "Analgésico paracetamol",
    "Anti-inflamatório ibuprofeno",
    "Anti-inflamatório nimesulida",
    "Antitérmico infantil",
    "Antialérgico",
    "Anti-histamínico",
    "Antibiótico venda com receita",
    "Antifúngico tópico",
    "Colírio lubrificante",
    "Colírio antialérgico",
    "Solução salina",
    "Descongestionante nasal",
    "Xarope expectorante",
    "Xarope para tosse",
    "Pastilha para garganta",
    "Spray para garganta",
    "Solução para gargarejo",
    "Protetor gástrico",
    "Antiácido",
    "Laxante",
    "Antidiarreico",
    "Probiótico",
    "Enzima digestiva",
    "Regulador intestinal",
    "Sal de fruta",
    "Chá digestivo",
    "Antisséptico bucal",
    "Creme dental branqueador",
    "Creme dental sensibilidade",
    "Escova de dente",
    "Fio dental encerado",
    "Fio dental sabor",
    "Enxaguante bucal com flúor",
    "Kit clareamento dental caseiro",
    "Sabonete líquido corporal",
    "Sabonete em barra",
    "Sabonete infantil",
    "Sabonete íntimo feminino",
    "Sabonete íntimo masculino",
    "Sabonete antibacteriano",
    "Sabonete de glicerina",
    "Shampoo para farmácia",
    "Condicionador para farmácia",
    "Shampoo anticaspa medicinal",
    "Shampoo antiqueda",
    "Loção capilar",
    "Minoxidil",
    "Finasterida tópica",
    "Absorvente diário",
    "Absorvente com abas",
    "Absorvente noturno",
    "Absorvente reutilizável",
    "Coletor menstrual",
    "Calcinha absorvente",
    "Tampão",
    "Genérica",
  ],
  "Bebês": [
    "Berço portátil",
    "Berço com balanço",
    "Berço com dossel",
    "Mini berço",
    "Moisés",
    "Cercadinho",
    "Berço desmontável",
    "Colchão para berço",
    "Trocador de fraldas",
    "Móvel trocador",
    "Cômoda infantil bebê",
    "Guarda-roupa bebê",
    "Prateleira infantil",
    "Carrinho de bebê",
    "Carrinho gêmeo",
    "Carrinho três rodas",
    "Carrinho travel system",
    "Bebê conforto",
    "Cadeira para automóvel grupo 0",
    "Cadeira para automóvel grupo 1",
    "Cadeira para automóvel grupo 2",
    "Cadeira para automóvel grupo 3",
    "Assento infantil elevado",
    "Espelho retrovisor infantil",
    "Protetor solar veicular infantil",
    "Tapa sol para carrinho",
    "Mosquiteiro para carrinho",
    "Capa de chuva para carrinho",
    "Bolsa organizadora para carrinho",
    "Ganchos organizadores",
    "Cadeirão de alimentação",
    "Cadeirão portátil",
    "Assento de mesa",
    "Prato ventosa",
    "Talheres de silicone",
    "Copo antivazamento",
    "Mamadeira anticólica",
    "Mamadeira de vidro",
    "Chupeta ortodôntica",
    "Chupeta prendedor",
    "Chocalho",
    "Fralda RN",
    "Fralda P",
    "Fralda M",
    "Fralda G",
    "Fralda de piscina",
    "Fralda de pano moderna",
    "Lenço umedecido",
    "Sabonete para bebê",
    "Shampoo infantil",
    "Colônia infantil",
    "Talco antisséptico",
    "Óleo para banho",
    "Creme para assadura",
    "Creme para prevenção",
    "Loção hidratante infantil",
    "Genérica",
  ],
  "Brinquedos": [
    "Boneca",
    "Boneca de pano",
    "Boneca reborn",
    "Boneca Barbie",
    "Boneco Ken",
    "Boneca Polly",
    "Boneca LOL",
    "Boneca Baby Alive",
    "Boneca articulada",
    "Boneco Batman",
    "Boneco Homem-Aranha",
    "Boneco Vingadores",
    "Boneco Star Wars",
    "Boneco Homem de Ferro",
    "Boneco Hulk",
    "Boneco Naruto",
    "Boneco Dragon Ball",
    "Boneco Pokémon",
    "Boneco One Piece",
    "Carrinho Hot Wheels",
    "Carrinho de controle remoto",
    "Carro elétrico infantil",
    "Moto elétrica infantil",
    "Trator infantil",
    "Caminhão de brinquedo",
    "Ônibus de brinquedo",
    "Trenzinho elétrico",
    "Bicicleta infantil aro 12",
    "Bicicleta infantil aro 16",
    "Bicicleta infantil aro 20",
    "Bicicleta com rodinhas",
    "Triciclo",
    "Patinete infantil",
    "Patins in-line infantil",
    "Skate infantil",
    "Prancha de surf infantil",
    "Jogos de tabuleiro clássicos",
    "Banco Imobiliário",
    "Detetive",
    "War",
    "Damas",
    "Xadrez",
    "Gamão",
    "Cubo mágico",
    "Torre de blocos",
    "Jogo da vida",
    "Uno",
    "Cards Against Humanity",
    "Quebra-cabeça 100 peças",
    "Quebra-cabeça 500 peças",
    "Quebra-cabeça 1000 peças",
    "Quebra-cabeça 3D",
    "Quebra-cabeça infantil grande",
    "Blocos de montar",
    "LEGO Classic",
    "LEGO City",
    "Genérica",
  ],
  "Pet Shop": [
    "Ração para cachorro adulto",
    "Ração para cachorro filhote",
    "Ração para cachorro sênior",
    "Ração super premium",
    "Ração natural",
    "Ração para raças pequenas",
    "Ração para raças grandes",
    "Ração hipoalergênica",
    "Ração para gatos adultos",
    "Ração para gatos filhotes",
    "Ração para gatos castrados",
    "Ração para gato sênior",
    "Ração úmida sachê",
    "Petisco para cachorro",
    "Bifinho",
    "Osso mordedor",
    "Osso natural defumado",
    "Snack dental",
    "Petisco natural",
    "Petisco para gato",
    "Erva-do-gato",
    "Coleira para cachorro",
    "Coleira antipulgas",
    "Coleira peitoral",
    "Guia para cachorro",
    "Guia retrátil",
    "Coleira e guia para gato",
    "Peitoral para cachorro",
    "Guia dupla",
    "Focinheira",
    "Cama para cachorro",
    "Cama para gato",
    "Almofada pet",
    "Casinha para cachorro",
    "Casinha para gato",
    "Toca de pelúcia",
    "Rede para gato",
    "Arranhador para gato",
    "Torre para gato",
    "Poste arranhador",
    "Comedouro plástico",
    "Comedouro inox",
    "Comedouro elevado",
    "Bebedouro fonte",
    "Bebedouro automático",
    "Bebedouro pet",
    "Alimentador automático",
    "Recipiente para ração",
    "Areia higiênica",
    "Areia sanitária granulada",
    "Areia de sílica",
    "Caixa de areia fechada",
    "Caixa de areia aberta",
    "Bandeja sanitária",
    "Pá para areia",
    "Tapete higiênico",
    "Genérica",
  ],
  "Esportes e Fitness": [
    "Bicicleta ergométrica",
    "Esteira elétrica",
    "Elíptico",
    "Bike spinning",
    "Simulador de escada",
    "Remo residencial",
    "Bicicleta indoor",
    "Halter",
    "Kit halteres",
    "Barras olímpicas",
    "Anilhas de ferro",
    "Anilhas de borracha",
    "Rack de agachamento",
    "Banco supino",
    "Banco reclinável",
    "Estação multifuncional",
    "Multifuncional para academia",
    "Kettlebell",
    "Bola de pilates",
    "Bola suíça",
    "Bola medicine ball",
    "Bosu",
    "Mini banda",
    "Faixa elástica",
    "TRX",
    "Corda naval",
    "Corda de pular",
    "Escada de agilidade",
    "Cone de treino",
    "Colchonete de yoga",
    "Bloco de yoga",
    "Cinto de yoga",
    "Rolo de liberação miofascial",
    "Bola de liberação",
    "Almofada de meditação",
    "Bola de futebol campo",
    "Bola de futsal",
    "Bola society",
    "Bola society profissional",
    "Bola de vôlei",
    "Bola de basquete",
    "Bola de handebol",
    "Bola de basquete infantil",
    "Bola de rugby",
    "Bola de futebol americano",
    "Trave de futebol",
    "Cesta de basquete",
    "Rede de vôlei",
    "Poste de vôlei",
    "Rede de badminton",
    "Kit de badminton",
    "Peteca",
    "Frisbee",
    "Tênis de corrida amortecimento",
    "Tênis de corrida neutro",
    "Tênis para trilha",
    "Genérica",
  ],
  "Pesca, Camping e Lazer": [
    "Vara de pesca telescópica",
    "Vara de pesca de carbono",
    "Vara para pesca oceânica",
    "Vara para pesca de água doce",
    "Molinete",
    "Carretilha",
    "Linha monofilamento",
    "Linha multifilamento",
    "Linha fluorocarbono",
    "Anzol",
    "Anzol tresmalho",
    "Chumbada",
    "Boia",
    "Empate",
    "Snap",
    "Girador",
    "Isca artificial",
    "Isca de silicone",
    "Isca de superfície",
    "Jig",
    "Spinner",
    "Isca para pesca em rio",
    "Isca para pesca oceânica",
    "Isca viva",
    "Camarão para isca",
    "Rede de pesca",
    "Puçá",
    "Landing net",
    "Caixa organizadora de iscas",
    "Caixa térmica para pesca",
    "Multi ferramentas pesca",
    "Alicate para pesca",
    "Faca de pesca",
    "Kit primeiros socorros pesca",
    "Barraca 2 pessoas",
    "Barraca 4 pessoas",
    "Barraca 6 pessoas",
    "Barraca familiar",
    "Barraca ultralight",
    "Barraca instantânea",
    "Barraca para trekking",
    "Barraca para praia",
    "Cobertura para carro",
    "Estrutura de acampamento",
    "Saco de dormir",
    "Colchonete inflável",
    "Colchão de camping",
    "Rede de descanso",
    "Rede com mosquiteiro",
    "Cadeira de camping",
    "Mesa dobrável para camping",
    "Kit talheres camping",
    "Panela camping",
    "Fogareiro",
    "Cartucho de gás",
    "Lanterna de cabeça",
    "Genérica",
  ],
  "Livros, Papelaria e Armarinho": [
    "Livro de romance",
    "Livro de ficção",
    "Livro de ficção científica",
    "Livro infantojuvenil",
    "Livro didático ensino médio",
    "Livro didático ensino fundamental",
    "Livro paradidático",
    "Livro de literatura brasileira",
    "Livro de literatura estrangeira",
    "Livro de autoajuda",
    "Livro de biografia",
    "Livro de história",
    "Livro de filosofia",
    "Livro de sociologia",
    "Livro de administração",
    "Livro de marketing",
    "Livro de finanças",
    "Livro de investimentos",
    "Livro de programação",
    "Livro técnico",
    "Livro de engenharia",
    "Livro de medicina",
    "Livro de direito",
    "Livro de psicologia",
    "Livro de pedagogia",
    "Livro religioso",
    "Bíblia sagrada",
    "Bíblia de estudo",
    "Livro sobre saúde",
    "Livro em inglês",
    "Livro em espanhol",
    "E-book",
    "Audiobook",
    "Livro em braille",
    "Livro pop-up",
    "Livro para colorir",
    "Revista em quadrinhos",
    "Mangá",
    "Caderno universitário",
    "Caderno espiral",
    "Caderno pequeno",
    "Caderno de desenho",
    "Caderno de caligrafia",
    "Caderno pautado",
    "Fichário",
    "Refil para fichário",
    "Caderno cartonado",
    "Agenda",
    "Planner",
    "Caneta esferográfica",
    "Caneta gel",
    "Caneta tinteiro",
    "Caneta hidrográfica",
    "Caneta permanente",
    "Marca-texto",
    "Caneta pincel",
    "Genérica",
  ],
  "Instrumentos Musicais": [
    "Violão acústico",
    "Violão clássico",
    "Violão elétrico",
    "Violão folk",
    "Violino 4/4",
    "Violino 3/4",
    "Violino infantil",
    "Viola caipira",
    "Viola clássica",
    "Violoncelo",
    "Contrabaixo acústico",
    "Guitarra Stratocaster",
    "Guitarra Les Paul",
    "Guitarra Telecaster",
    "Guitarra semi-acústica",
    "Guitarra 7 cordas",
    "Guitarra baixo 4 cordas",
    "Guitarra baixo 5 cordas",
    "Guitarra baixo 6 cordas",
    "Baixolão",
    "Ukulele soprano",
    "Ukulele concert",
    "Ukulele tenor",
    "Cavaquinho",
    "Banjo",
    "Bandolim",
    "Bandolim elétrico",
    "Pandeiro",
    "Tamborim",
    "Cuíca",
    "Rebeque",
    "Bateria acústica completa",
    "Bateria eletrônica",
    "Prato de bateria",
    "Prato hi-hat",
    "Prato crash",
    "Prato ride",
    "Bumbo",
    "Caixa de bateria",
    "Tom",
    "Surdo",
    "Chimbal",
    "Suporte para bateria",
    "Pedal duplo bateria",
    "Pedal simples bateria",
    "Baqueta",
    "Vassourinha",
    "Feltro para bateria",
    "Teclado 61 teclas",
    "Teclado 76 teclas",
    "Teclado 88 teclas",
    "Piano acústico vertical",
    "Piano digital",
    "Piano de cauda",
    "Órgão eletrônico",
    "Sintetizador",
    "Genérica",
  ],
  "Indústria e Comércio": [
    "Empilhadeira elétrica",
    "Empilhadeira a combustão",
    "Empilhadeira manual",
    "Paleteira elétrica",
    "Paleteira manual",
    "Transpaleteira",
    "Escada extensível industrial",
    "Andaime tubular",
    "Andaime multidirecional",
    "Andaime suspenso",
    "Estante para armazenagem",
    "Estante de aço leve",
    "Estante de aço pesada",
    "Porta pallet",
    "Pallet PBR",
    "Pallet de plástico",
    "Contêiner metálico",
    "Contêiner marítimo",
    "Big bag",
    "Caixa organizadora industrial",
    "Balança industrial",
    "Balança de plataforma",
    "Balança para pallet",
    "Balança rodoviária",
    "Selo lacre",
    "Etiquetadora industrial",
    "Impressora térmica industrial",
    "Leitor de código de barras",
    "Coletor de dados",
    "PDV completo",
    "Registradora",
    "Impressora fiscal",
    "Gaveta de dinheiro",
    "Testador de nota",
    "Bobina para impressora fiscal",
    "Bobina térmica",
    "Vitrine expositora",
    "Balcão refrigerado comercial",
    "Balcão estufa",
    "Balcão neutro",
    "Ilha refrigerada",
    "Freezer expositor vertical",
    "Freezer horizontal comercial",
    "Refrigerador expositor vertical",
    "Buffet refrigerado",
    "Adega comercial",
    "Cadeira executiva",
    "Mesa para escritório 1,20m",
    "Mesa L",
    "Estação de trabalho",
    "Mesa de reunião",
    "Armário para escritório",
    "Gaveteiro para escritório",
    "Cadeira para recepção",
    "Sofá recepção",
    "Painel divisor de ambiente",
    "Genérica",
  ],
  "Agro e Pecuária": [
    "Semente de soja",
    "Semente de milho",
    "Semente de trigo",
    "Semente de arroz",
    "Semente de feijão",
    "Semente de sorgo",
    "Semente de aveia",
    "Semente de girassol",
    "Semente de algodão",
    "Semente de café",
    "Muda de cafeeiro",
    "Muda de eucalipto",
    "Muda frutífera",
    "Muda de citros",
    "Muda de cacau",
    "Muda de banana",
    "Adubo NPK",
    "Adubo orgânico",
    "Adubo foliar",
    "Ureia",
    "Fosfato de rocha",
    "Calcário dolomítico",
    "Gesso agrícola",
    "Biofertilizante",
    "Composto orgânico",
    "Húmus de minhoca",
    "Herbicida",
    "Inseticida",
    "Fungicida",
    "Acaricida",
    "Nematicida",
    "Formicida",
    "Cupinicida",
    "Defensivo natural",
    "Óleo mineral agrícola",
    "Espalhante adesivo",
    "Ração para bovinos",
    "Ração para suínos",
    "Ração para aves",
    "Ração para equinos",
    "Ração para peixes de aquicultura",
    "Sal mineral bovino",
    "Sal proteinado",
    "Suplemento mineral",
    "Concentrado proteico",
    "Silagem de milho",
    "Silagem de sorgo",
    "Feno de tifton",
    "Feno de coast cross",
    "Cana picada",
    "Palhada",
    "Casca de arroz",
    "Cerca elétrica",
    "Fio para cerca elétrica",
    "Isolador cerca elétrica",
    "Aparelho de cerca elétrica",
    "Genérica",
  ],
  "Jardim, Piscinas e Área Externa": [
    "Mangueira de jardim",
    "Mangueira retrátil",
    "Esguicho para mangueira",
    "Aspersor rotativo",
    "Aspersor pop-up",
    "Sistema de irrigação automática",
    "Filtro para mangueira",
    "Conexão para mangueira",
    "Programador de irrigação",
    "Regador manual",
    "Regador automático",
    "Borrifador",
    "Adubo para plantas",
    "Adubo NPK jardim",
    "Fertilizante líquido para plantas",
    "Adubo para orquídeas",
    "Fertilizante para gramados",
    "Vaso de plástico",
    "Vaso de barro",
    "Vaso de cimento",
    "Vaso de fibra",
    "Vaso auto irrigável",
    "Cachepot decorativo",
    "Floreira",
    "Suporte para vasos",
    "Tapete para vasos",
    "Prato para vasos",
    "Muda de rosa",
    "Muda de orquídea",
    "Muda de suculenta",
    "Muda de árvore frutífera",
    "Muda de eucalipto ornamental",
    "Sementes de horta",
    "Sementes de flores",
    "Sementes de gramado",
    "Grama esmeralda",
    "Grama são carlos",
    "Grama coreana",
    "Tapete de grama sintética",
    "Substrato para plantas",
    "Terra vegetal",
    "Húmus",
    "Casca de pinus",
    "Turfa",
    "Pedrisco decorativo",
    "Seixo",
    "Pedra portuguesa",
    "Argila expandida",
    "Cortador de grama elétrico",
    "Cortador de grama a gasolina",
    "Aparador de grama",
    "Roçadeira elétrica",
    "Roçadeira a gasolina",
    "Podador de galhos",
    "Tesoura de poda",
    "Tesoura elétrica",
    "Genérica",
  ],
  "Alimentos e Bebidas": [
    "Arroz branco tipo 1",
    "Arroz integral",
    "Arroz parboilizado",
    "Arroz basmati",
    "Arroz arbóreo",
    "Feijão carioca",
    "Feijão preto",
    "Feijão branco",
    "Feijão fradinho",
    "Lentilha",
    "Grão de bico",
    "Ervilha seca",
    "Farinha de trigo",
    "Farinha de mandioca",
    "Farinha de milho",
    "Farinha de rosca",
    "Farinha de coco",
    "Farinha de amêndoa",
    "Farinha de linhaça",
    "Fubá",
    "Amido de milho",
    "Polvilho azedo",
    "Polvilho doce",
    "Tapioca",
    "Cuscuz",
    "Macarrão espaguete",
    "Macarrão parafuso",
    "Macarrão penne",
    "Macarrão instantâneo",
    "Macarrão para lasanha",
    "Macarrão sem glúten",
    "Açúcar refinado",
    "Açúcar cristal",
    "Açúcar demerara",
    "Açúcar mascavo",
    "Açúcar de coco",
    "Adoçante líquido",
    "Adoçante em pó",
    "Xilitol",
    "Mel puro",
    "Melado de cana",
    "Xarope de bordo",
    "Óleo de soja",
    "Óleo de girassol",
    "Óleo de canola",
    "Azeite de oliva extra virgem",
    "Manteiga",
    "Margarina",
    "Banha",
    "Gordura vegetal",
    "Café torrado e moído tradicional",
    "Café espresso em grão",
    "Café gourmet",
    "Café descafeinado",
    "Café solúvel",
    "Cápsula compatível Nespresso",
    "Genérica",
  ],
  "Festas e Eventos": [
    "Balão de látex 5 polegadas",
    "Balão de látex 9 polegadas",
    "Balão metalizado",
    "Balão de números",
    "Balão de letras",
    "Balão bubble",
    "Kit balões",
    "Bomba para balão",
    "Suporte para balões",
    "Arco de balões",
    "Painel para festa",
    "Painel redondo",
    "Painel retangular",
    "Painel personalizado",
    "Backdrop",
    "Cortina de fita",
    "Cortina metalizada",
    "Cortina de coração",
    "Fundo para festa",
    "Toalha para mesa festa",
    "Trilho de mesa festa",
    "Guardanapo festa",
    "Prato descartável tema",
    "Copo descartável tema",
    "Talher descartável tema",
    "Sacolinha para lembrancinha",
    "Caixa para lembrancinha",
    "Kit personalizado festa",
    "Bolo cenográfico",
    "Suporte para bolo",
    "Corte para bolo",
    "Vela numerada",
    "Vela sparkler",
    "Vela candelabro",
    "Vela decorativa",
    "Vela de aniversário",
    "Decoração de festa infantil",
    "Tema safari",
    "Tema princesa",
    "Tema super-heróis",
    "Tema unicórnio",
    "Tema fazendinha",
    "Tema chá revelação",
    "Tema chá de bebê",
    "Tema chá de fralda",
    "Tema chá bar",
    "Tema noivado",
    "Tema casamento",
    "Tema formatura",
    "Confete de festa",
    "Serpentina",
    "Chuva de prata",
    "Guirlanda de bandeirolas",
    "Guirlanda personalizada",
    "Bandeirola de tecido",
    "Painel dourado",
    "Genérica",
  ],
  "Serviços": [
    "Serviço de eletricista residencial",
    "Serviço de encanador",
    "Serviço de pedreiro",
    "Serviço de pintor",
    "Serviço de gesseiro",
    "Serviço de marceneiro",
    "Serviço de vidraceiro",
    "Serviço de serralheiro",
    "Serviço de montador de móveis",
    "Serviço de desentupidora",
    "Serviço de dedetização",
    "Serviço de descupinização",
    "Serviço de limpeza de fossa",
    "Serviço de limpeza pós obra",
    "Serviço de faxina residencial",
    "Serviço de diarista",
    "Serviço de faxina comercial",
    "Serviço de limpeza de vidros",
    "Serviço de limpeza de estofados",
    "Serviço de limpeza de piscinas",
    "Serviço de jardinagem",
    "Serviço de poda de árvores",
    "Serviço de paisagismo",
    "Serviço de instalação de grama",
    "Serviço de manutenção de gramado",
    "Serviço de controle de pragas em plantas",
    "Serviço de manutenção elétrica",
    "Serviço de manutenção hidráulica",
    "Serviço de instalação de ar condicionado",
    "Serviço de manutenção de ar condicionado",
    "Serviço de limpeza de ar condicionado",
    "Serviço de recarga de ar condicionado",
    "Serviço de assistência de eletrodoméstico",
    "Serviço de conserto de máquina de lavar",
    "Serviço de conserto de geladeira",
    "Serviço de conserto de forno",
    "Serviço de conserto de fogão",
    "Serviço de reforma residencial",
    "Serviço de reforma comercial",
    "Serviço de construção de piscina",
    "Serviço de instalação de piso",
    "Serviço de instalação de porcelanato",
    "Serviço de instalação de forro de gesso",
    "Serviço de instalação de drywall",
    "Serviço de impermeabilização",
    "Serviço de restauração de fachada",
    "Serviço de fotografia de casamento",
    "Serviço de fotografia infantil",
    "Serviço de fotografia gestante",
    "Serviço de fotografia de eventos",
    "Serviço de fotografia corporativa",
    "Serviço de filmagem para eventos",
    "Serviço de edição de vídeo",
    "Serviço de drone para eventos",
    "Serviço de estúdio fotográfico",
    "Serviço de aulas particulares de matemática",
    "Genérica",
  ],
  "Escritório e Empresas": [
    "Papel A4 branco 500 folhas",
    "Papel A4 colorido",
    "Papel para impressão fotográfica",
    "Papel almaço",
    "Papel carta",
    "Papel autocopiativo",
    "Papel para fax",
    "Papel timbrado personalizado",
    "Toner HP",
    "Toner Brother",
    "Toner Samsung",
    "Toner Xerox",
    "Cartucho HP",
    "Cartucho Canon",
    "Cartucho Epson",
    "Refil para tinta",
    "Impressora multifuncional a laser",
    "Impressora colorida jato de tinta",
    "Grampeador escritório",
    "Grampeador industrial",
    "Furador de papel escritório",
    "Perfurador com dispenser",
    "Grampos para grampeador",
    "Extrator de grampos",
    "Cola bastão escritório",
    "Fita adesiva escritório",
    "Caneta esferográfica azul escritório",
    "Caneta esferográfica preta escritório",
    "Caneta esferográfica vermelha escritório",
    "Marca-texto escritório",
    "Corretor líquido",
    "Corretor em fita",
    "Borracha branca",
    "Apontador com depósito",
    "Pasta suspensa",
    "Pasta AZ",
    "Pasta plástica",
    "Pasta cartonada",
    "Envelope A4 escritório",
    "Envelope ofício",
    "Envelope kraft para envio",
    "Envelope plástico bolha",
    "Etiqueta adesiva A4",
    "Etiqueta para pacotes",
    "Etiqueta térmica escritório",
    "Mesa executiva",
    "Mesa de reunião oval",
    "Mesa em L",
    "Mesa reta 1,20m",
    "Mesa de escritório home office",
    "Estação de trabalho compartilhada",
    "Cadeira giratória",
    "Cadeira presidente",
    "Cadeira interlocutor",
    "Cadeira de reunião",
    "Cadeira ergonômica",
    "Genérica",
  ],
  "Artesanato e Hobby": [
    "Kit crochê iniciante",
    "Kit tricô iniciante",
    "Kit macramê",
    "Kit costura básica",
    "Kit bordado ponto cruz",
    "Kit bordado livre",
    "Kit tapeçaria",
    "Kit ponto americano",
    "Kit almofada em crochê",
    "Fio para amigurumi",
    "Fio de malha",
    "Fio de barbante",
    "Fio de algodão",
    "Fio para tricô",
    "Novelo de lã",
    "Fio decorativo",
    "Fio metálico",
    "Fio encerado",
    "Fio de sisal",
    "Agulha de crochê 2mm",
    "Agulha de crochê 3mm",
    "Agulha de crochê 4mm",
    "Kit agulhas de tricô",
    "Agulha para tapeçaria",
    "Agulha para bordado",
    "Bastidor de bordado",
    "Tesoura para bordado",
    "Marcador de pontos",
    "Contador de carreiras",
    "Tinta acrílica para arte 60ml",
    "Tinta acrílica 250ml",
    "Tinta óleo em bisnaga",
    "Tinta guache infantil",
    "Aquarela líquida",
    "Tinta para tecido",
    "Tinta para vidro",
    "Tinta para porcelana",
    "Tinta para cerâmica",
    "Tinta relevo",
    "Tinta glitter",
    "Tinta puff",
    "Pincel redondo",
    "Pincel chato",
    "Pincel para aquarela",
    "Pincel para óleo",
    "Kit pincéis de arte",
    "Espátula para pintura",
    "Paleta para tintas",
    "Cavalete de mesa",
    "Cavalete de chão",
    "Bloco para desenho",
    "Papel canson A4",
    "Papel canson A3",
    "Tela para pintura",
    "Bastidor com tela",
    "Tela em MDF",
    "Genérica",
  ],
  "Colecionáveis e Antiguidades": [
    "Moeda antiga brasileira",
    "Moeda comemorativa",
    "Moeda estrangeira antiga",
    "Cédula antiga",
    "Cédula estrangeira",
    "Álbum de moedas",
    "Álbum de cédulas",
    "Kit numismática iniciante",
    "Lupa numismática",
    "Guia numismático",
    "Selo comemorativo",
    "Selo antigo brasileiro",
    "Selo estrangeiro",
    "Álbum de selos",
    "Pinça filatélica",
    "Guia filatélico",
    "Estojo para selos",
    "Miniatura de carro 1:18",
    "Miniatura de carro 1:24",
    "Miniatura de carro 1:43",
    "Miniatura de carro 1:64",
    "Miniatura Hot Wheels colecionável",
    "Miniatura Bburago",
    "Miniatura Maisto",
    "Miniatura de moto",
    "Miniatura de caminhão",
    "Miniatura de avião",
    "Miniatura de helicóptero",
    "Miniatura de trator",
    "Miniatura militar",
    "Action figure Marvel",
    "Action figure DC",
    "Action figure Star Wars",
    "Action figure Naruto",
    "Action figure Dragon Ball",
    "Action figure One Piece",
    "Action figure Pokémon",
    "Action figure Attack on Titan",
    "Action figure Hot Toys",
    "Estátua colecionável",
    "Funko Pop Marvel",
    "Funko Pop DC",
    "Funko Pop Star Wars",
    "Funko Pop Harry Potter",
    "Funko Pop música",
    "Funko Pop filmes",
    "Funko Pop games",
    "Funko Pop chase",
    "Funko Pop exclusivo",
    "Card colecionável Magic",
    "Card colecionável Pokémon",
    "Card colecionável Yu-Gi-Oh",
    "Card colecionável Dragon Ball",
    "Card colecionável esporte",
    "Pack booster",
    "Deck estratégico",
    "Genérica",
  ],
  "Outros": [
    "Produto para revenda geral",
    "Achado importado",
    "Artigo diverso",
    "Curiosidade",
    "Item para presente",
    "Item para colecionador iniciante",
    "Item promocional",
    "Produto premium sem categoria",
    "Produto econômico sem categoria",
    "Produto para uso pessoal",
    "Kit revenda multiuso",
    "Kit misto para revenda",
    "Achados de importados dos EUA",
    "Achados de importados da China",
    "Achados de importados do Paraguai",
    "Achados de importados do Japão",
    "Produto sazonal geral",
    "Achado raro",
    "Achado promocional",
    "Kit para presente amigo secreto",
    "Item para papelaria criativa",
    "Item para lembrancinha diversa",
    "Item para decoração alternativa",
    "Item para presente corporativo diverso",
    "Item para brinde diverso",
    "Produto para venda porta a porta",
    "Produto para venda em bazar",
    "Produto para venda em feira",
    "Produto artesanal diverso",
    "Produto handmade personalizado",
    "Produto sustentável genérico",
    "Produto ecológico geral",
    "Produto biodegradável",
    "Produto reciclado",
    "Produto ecodesign",
    "Produto reutilizável",
    "Objeto de decoração alternativo",
    "Objeto de arte diverso",
    "Escultura diversa",
    "Peça única",
    "Objeto colecionável diverso",
    "Peça vintage geral",
    "Peça retrô diversa",
    "Peça industrial diversa",
    "Peça geek",
    "Peça nerd",
    "Item de utilidade doméstica geral",
    "Item multifuncional",
    "Item inovador",
    "Item tecnológico diverso",
    "Gadget diverso",
    "Kit gadget",
    "Kit surpresa",
    "Caixa mistério",
    "Caixa surpresa",
    "Item para hobby geral",
    "Genérica",
  ],
};

export const ALL_CATEGORIES = Object.keys(CATEGORIES_TREE);
