export const CATEGORIES_TREE: Record<string, string[]> = {
  "Alimentos": [
    "Arroz",
    "Feijão",
    "Macarrão",
    "Lasanha",
    "Farinha",
    "Açúcar",
    "Sal",
    "Café",
    "Chá",
    "Achocolatado",
    "Biscoito",
    "Bolacha",
    "Cereal",
    "Granola",
    "Aveia",
    "Tapioca",
    "Cuscuz",
    "Polenta",
    "Trigo",
    "Centeio",
    "Milho",
    "Soja",
    "Lentilha",
    "Grão de Bico",
    "Quinoa",
    "Amido",
    "Fubá",
    "Farofa",
    "Mel",
    "Geleia",
    "Azeite",
    "Óleo de Coco",
    "Manteiga",
    "Margarina",
    "Requeijão",
    "Cream Cheese",
    "Iogurte",
    "Leite Condensado",
    "Creme de Leite",
    "Massa de Pizza",
    "Pão de Forma",
    "Torrada",
    "Bolo",
    "Brownie",
    "Cookie",
    "Wafer",
    "Pipoca",
    "Salgadinho",
    "Amendoim",
    "Castanha",
    "Nozes",
    "Avelã",
    "Pistache",
    "Damasco"
  ],
  "Bebidas": [
    "Coca",
    "Pepsi",
    "Guaraná",
    "Fanta",
    "Sprite",
    "Suco de Laranja",
    "Suco de Uva",
    "Suco de Maçã",
    "Suco de Caju",
    "Suco de Manga",
    "Suco Verde",
    "Água Mineral",
    "Água com Gás",
    "Energético",
    "Isotônico",
    "Cerveja Pilsen",
    "Cerveja IPA",
    "Cerveja Weiss",
    "Cerveja Stout",
    "Vinho Tinto",
    "Vinho Branco",
    "Vinho Rosé",
    "Espumante",
    "Champagne",
    "Vodka",
    "Whisky",
    "Gin",
    "Rum",
    "Cachaça",
    "Tequila",
    "Saquê",
    "Licor",
    "Vermute",
    "Aperitivo",
    "Conhaque",
    "Hidromel",
    "Kombucha",
    "Chá Gelado",
    "Refrigerante Diet",
    "Refrigerante Zero",
    "Mate",
    "Café Pronto",
    "Achocolatado Pronto",
    "Bebidas Tradicional 190"
  ],
  "Hortifruti": [
    "Hortifruti - Artesanal Zero",
    "Série Hortifruti Mini",
    "Hortifruti Modelo Térmico 109",
    "Hortifruti Tradicional 24",
    "Pack Hortifruti Nylon",
    "Hortifruti Linha Sem Fio 51",
    "Hortifruti Combo Zero 115",
    "Hortifruti Edição Premium 195",
    "Série Hortifruti Silicone",
    "Hortifruti - Gourmet Retro",
    "Tipo Hortifruti Colorido",
    "Hortifruti Resistente 98",
    "Hortifruti Preto 89",
    "Hortifruti Edição Compacto 187",
    "Tricô para Hortifruti #32",
    "Reforçado para Hortifruti #142",
    "Hortifruti - Antialérgico Cinza",
    "Hortifruti Coleção Ecológico 12",
    "Tipo Hortifruti Doméstico",
    "Hortifruti Orgânico 26",
    "Gourmet para Hortifruti #117",
    "Hortifruti - Luxo Dourado",
    "Hortifruti - Light Caseiro",
    "Hortifruti Ergonômico 163",
    "Sortido Hortifruti Artesanal",
    "Estojo Hortifruti Prata",
    "Hortifruti - Sem Fio Zero",
    "Hortifruti - Inteligente Orgânico",
    "Hortifruti Elegante 103",
    "Hortifruti - Ecológico Diet",
    "Hortifruti Kit Diet 168",
    "Inox para Hortifruti #165",
    "Vintage para Hortifruti #68",
    "Pack Hortifruti Sem Fio",
    "Hortifruti Edição Solar 110",
    "Hortifruti Combo Cinza 57",
    "Sortido Hortifruti Poliéster",
    "Hortifruti Portátil 29",
    "Modelo Hortifruti Luxo",
    "Anatômico para Hortifruti #17",
    "Prata para Hortifruti #153",
    "Microfibra para Hortifruti #65",
    "Hortifruti Linha Maxi 175",
    "Hortifruti Edição Colorido 29"
  ],
  "Padaria e Confeitaria": [
    "Padaria e Confeitaria - Cerâmica Luxo",
    "Premium para Padaria e Confeitaria #185",
    "Padaria e Confeitaria - Nylon Familiar",
    "Padaria e Confeitaria Modelo Esportivo 164",
    "Padaria e Confeitaria Coleção Retro 96",
    "Sortido Padaria e Confeitaria Microfibra",
    "Padaria e Confeitaria Anatômico 83",
    "Moderno para Padaria e Confeitaria #29",
    "Padaria e Confeitaria - Casual Natural",
    "Padaria e Confeitaria Natural 146",
    "Padaria e Confeitaria Reforçado 188",
    "Ecológico para Padaria e Confeitaria #195",
    "Padaria e Confeitaria Tipo Plus 169",
    "Recarregável para Padaria e Confeitaria #43",
    "Padaria e Confeitaria - Microfibra Ergonômico",
    "Diet para Padaria e Confeitaria #139",
    "Série Padaria e Confeitaria Casual",
    "Dourado para Padaria e Confeitaria #113",
    "Padaria e Confeitaria Versão Slim 64",
    "Conjunto Padaria e Confeitaria Colorido",
    "Padaria e Confeitaria Térmico 142",
    "Edição Padaria e Confeitaria Zero",
    "Padaria e Confeitaria Sustentável 182",
    "Padaria e Confeitaria Orgânico 18",
    "Padaria e Confeitaria Minimalista 19",
    "Padaria e Confeitaria Coleção Gourmet 172",
    "Série Padaria e Confeitaria Wi-Fi",
    "Padaria e Confeitaria Versão Artesanal 122",
    "Adulto para Padaria e Confeitaria #25",
    "Padaria e Confeitaria Cerâmica 91",
    "Madeira para Padaria e Confeitaria #120",
    "Padaria e Confeitaria Ultra 16",
    "Colorido para Padaria e Confeitaria #28",
    "Pack Padaria e Confeitaria Adulto",
    "Padaria e Confeitaria Versão Eco 109",
    "Coleção Padaria e Confeitaria Couro",
    "Tamanho Padaria e Confeitaria Sustentável",
    "Recarregável para Padaria e Confeitaria #26",
    "Padaria e Confeitaria Crochê 4",
    "Padaria e Confeitaria Natural 43",
    "Seda para Padaria e Confeitaria #124",
    "Tamanho Padaria e Confeitaria Bambu",
    "Padaria e Confeitaria Econômico 98",
    "Padaria e Confeitaria Cobre 68"
  ],
  "Congelados": [
    "Industrial para Congelados #109",
    "Congelados Versão Retro 49",
    "Congelados - Diet Inteligente",
    "Congelados Sortido Inteligente 192",
    "Congelados - Inteligente Portátil",
    "Congelados Versão Nylon 136",
    "Kit Congelados Veludo",
    "Congelados Infantil 18",
    "Congelados Modelo Natural 104",
    "Congelados Bluetooth 64",
    "Congelados Linha Antialérgico 21",
    "Solar para Congelados #145",
    "Congelados Kit Nacional 53",
    "Congelados - Natural Nacional",
    "Plus para Congelados #172",
    "Congelados - Metal Elegante",
    "Congelados Clássico 118",
    "Congelados Modelo Sustentável 138",
    "Sortido Congelados Nacional",
    "Versão Congelados Branco",
    "Congelados Artesanal 95",
    "Congelados - Luxo Vidro",
    "Congelados Edição Antiderrapante 168",
    "Congelados Linha Recarregável 77",
    "Congelados Eco 68",
    "Congelados Mini 191",
    "Congelados Tipo Caseiro 73",
    "Congelados Coleção Colorido 53",
    "Congelados - Nylon Seda",
    "Congelados - Portátil Resistente",
    "Gourmet para Congelados #12",
    "Congelados Minimalista 198",
    "Modelo Congelados Nacional",
    "Série Congelados Vidro",
    "Congelados Combo Sem Fio 3",
    "Congelados Sustentável 177",
    "Sortido Congelados Profissional",
    "Congelados - Solar Recarregável",
    "Caixa Congelados Plus",
    "Congelados Casual 94",
    "Congelados Preto 54",
    "Modelo Congelados Mini",
    "Congelados - Sem Fio Madeira",
    "Congelados Tipo Natural 42"
  ],
  "Mercearia Gourmet": [
    "Versão Mercearia Gourmet Madeira",
    "Mercearia Gourmet Familiar 189",
    "Mercearia Gourmet - Madeira Artesanal",
    "Mercearia Gourmet - Luxo Mini",
    "Profissional para Mercearia Gourmet #121",
    "Pack Mercearia Gourmet Metal",
    "Mercearia Gourmet - Casual Orgânico",
    "Kit Mercearia Gourmet Adulto",
    "Minimalista para Mercearia Gourmet #72",
    "Mercearia Gourmet Gourmet 90",
    "Mercearia Gourmet Combo Tricô 85",
    "Mercearia Gourmet Maxi 67",
    "Edição Mercearia Gourmet Nacional",
    "Mercearia Gourmet Mini 153",
    "Branco para Mercearia Gourmet #187",
    "Mercearia Gourmet - Cerâmica Ergonômico",
    "Mercearia Gourmet Modelo Cobre 148",
    "Coleção Mercearia Gourmet Compacto",
    "Premium para Mercearia Gourmet #134",
    "Mercearia Gourmet Coleção Cinza 111",
    "Mercearia Gourmet Minimalista 160",
    "Mercearia Gourmet - Slim Esportivo",
    "Mercearia Gourmet Edição Madeira 84",
    "Doméstico para Mercearia Gourmet #142",
    "Pack Mercearia Gourmet Plástico",
    "Familiar para Mercearia Gourmet #158",
    "Mercearia Gourmet Edição Bambu 141",
    "Mercearia Gourmet Esportivo 74",
    "Caixa Mercearia Gourmet Solar",
    "Mercearia Gourmet Kit Couro 114",
    "Diet para Mercearia Gourmet #131",
    "Econômico para Mercearia Gourmet #169",
    "Mercearia Gourmet Industrial 132",
    "Mercearia Gourmet Kit Resistente 193",
    "Modelo Mercearia Gourmet Casual",
    "Tipo Mercearia Gourmet Premium Gold",
    "Kit Mercearia Gourmet Compacto",
    "Estojo Mercearia Gourmet Antiderrapante",
    "Mercearia Gourmet Metal 107",
    "Mercearia Gourmet Coleção Cobre 127",
    "Artesanal para Mercearia Gourmet #38",
    "Mercearia Gourmet Mini 109",
    "Linha Mercearia Gourmet Camurça",
    "Portátil para Mercearia Gourmet #143"
  ],
  "Limpeza": [
    "Versão Limpeza Slim",
    "Eco para Limpeza #119",
    "Limpeza Sortido Anatômico 82",
    "Antiderrapante para Limpeza #185",
    "Limpeza Combo Recarregável 115",
    "Série Limpeza Algodão",
    "Nacional para Limpeza #193",
    "Tamanho Limpeza Gourmet",
    "Limpeza Versão Natural 71",
    "Sustentável para Limpeza #183",
    "Limpeza - Natural Caseiro",
    "Limpeza - Elegante Crochê",
    "Limpeza Eco 39",
    "Caixa Limpeza Retro",
    "Conjunto Limpeza Plástico",
    "Minimalista para Limpeza #139",
    "Plástico para Limpeza #16",
    "Tamanho Limpeza Plástico",
    "Solar para Limpeza #179",
    "Limpeza Wi-Fi 98",
    "Premium para Limpeza #91",
    "Limpeza - Cobre Plástico",
    "Limpeza Sortido Ergonômico 57",
    "Zero para Limpeza #70",
    "Seda para Limpeza #8",
    "Colorido para Limpeza #172",
    "Econômico para Limpeza #120",
    "Edição Limpeza Tricô",
    "Limpeza Inox 152",
    "Limpeza Linha Reforçado 165",
    "Kit Limpeza Nacional",
    "Rústico para Limpeza #55",
    "Rústico para Limpeza #87",
    "Gourmet para Limpeza #193",
    "Importado para Limpeza #21",
    "Moderno para Limpeza #192",
    "Limpeza Linha Branco 58",
    "Limpeza Compacto 194",
    "Limpeza Artesanal 52",
    "Limpeza Antialérgico 40",
    "Linha Limpeza Algodão",
    "Limpeza Bluetooth 56",
    "Importado para Limpeza #197",
    "Limpeza - Econômico Ergonômico"
  ],
  "Higiene Pessoal": [
    "Higiene Pessoal Modelo Luxo 80",
    "Higiene Pessoal Solar 7",
    "Higiene Pessoal - Wi-Fi Prata",
    "Premium Gold para Higiene Pessoal #20",
    "Higiene Pessoal Coleção Mini 179",
    "Higiene Pessoal - Anatômico Slim",
    "Higiene Pessoal Linha Branco 137",
    "Dourado para Higiene Pessoal #18",
    "Higiene Pessoal Kit Clássico 108",
    "Mini para Higiene Pessoal #111",
    "Higiene Pessoal - Metal Retro",
    "Familiar para Higiene Pessoal #188",
    "Higiene Pessoal Edição Antiderrapante 138",
    "Couro para Higiene Pessoal #112",
    "Higiene Pessoal Edição Rústico 63",
    "Higiene Pessoal Gourmet 116",
    "Tipo Higiene Pessoal Couro",
    "Higiene Pessoal Combo Colorido 8",
    "Rústico para Higiene Pessoal #47",
    "Diet para Higiene Pessoal #91",
    "Higiene Pessoal - Colorido Gourmet",
    "Higiene Pessoal Edição Sem Fio 3",
    "Higiene Pessoal Coleção Reforçado 62",
    "Seda para Higiene Pessoal #143",
    "Série Higiene Pessoal Algodão",
    "Acrílico para Higiene Pessoal #5",
    "Higiene Pessoal Doméstico 57",
    "Artesanal para Higiene Pessoal #79",
    "Higiene Pessoal Kit Algodão 142",
    "Higiene Pessoal Kit Silicone 191",
    "Higiene Pessoal Kit Preto 180",
    "Caseiro para Higiene Pessoal #79",
    "Higiene Pessoal - Orgânico Slim",
    "Combo Higiene Pessoal Slim",
    "Higiene Pessoal Tipo Adulto 56",
    "Gourmet para Higiene Pessoal #186",
    "Higiene Pessoal Sortido Anatômico 73",
    "Higiene Pessoal Adulto 76",
    "Combo Higiene Pessoal Familiar",
    "Higiene Pessoal - Clássico Tricô",
    "Coleção Higiene Pessoal Compacto",
    "Higiene Pessoal Recarregável 75",
    "Modelo Higiene Pessoal Seda",
    "Higiene Pessoal Clássico 147"
  ],
  "Beleza e Cosméticos": [
    "Beleza e Cosméticos - Algodão Linho",
    "Colorido para Beleza e Cosméticos #48",
    "Beleza e Cosméticos Importado 123",
    "Beleza e Cosméticos Ecológico 103",
    "Sustentável para Beleza e Cosméticos #148",
    "Beleza e Cosméticos Retro 39",
    "Beleza e Cosméticos Edição Reforçado 64",
    "Beleza e Cosméticos Sem Fio 196",
    "Ergonômico para Beleza e Cosméticos #153",
    "Beleza e Cosméticos Coleção Camurça 98",
    "Vidro para Beleza e Cosméticos #77",
    "Beleza e Cosméticos Combo Casual 146",
    "Beleza e Cosméticos Linha Antiderrapante 190",
    "Beleza e Cosméticos Light 161",
    "Coleção Beleza e Cosméticos Reforçado",
    "Pack Beleza e Cosméticos Familiar",
    "Beleza e Cosméticos Modelo Luxo 1",
    "Acrílico para Beleza e Cosméticos #177",
    "Beleza e Cosméticos Versão Doméstico 9",
    "Coleção Beleza e Cosméticos Industrial",
    "Sustentável para Beleza e Cosméticos #176",
    "Versão Beleza e Cosméticos Nacional",
    "Beleza e Cosméticos Coleção Silicone 30",
    "Beleza e Cosméticos Coleção Retro 69",
    "Conjunto Beleza e Cosméticos Inteligente",
    "Tipo Beleza e Cosméticos Casual",
    "Beleza e Cosméticos Edição Vidro 32",
    "Esportivo para Beleza e Cosméticos #180",
    "Caseiro para Beleza e Cosméticos #129",
    "Beleza e Cosméticos Versão Vidro 21",
    "Beleza e Cosméticos Linha Cerâmica 189",
    "Beleza e Cosméticos - Ergonômico Importado",
    "Beleza e Cosméticos Resistente 59",
    "Beleza e Cosméticos Linha Caseiro 148",
    "Beleza e Cosméticos Familiar 121",
    "Beleza e Cosméticos Versão Gourmet 47",
    "Beleza e Cosméticos Combo Seda 24",
    "Branco para Beleza e Cosméticos #105",
    "Beleza e Cosméticos - Rústico Mini",
    "Combo Beleza e Cosméticos Madeira",
    "Industrial para Beleza e Cosméticos #170",
    "Recarregável para Beleza e Cosméticos #10",
    "Resistente para Beleza e Cosméticos #81",
    "Beleza e Cosméticos - Rústico Maxi"
  ],
  "Perfumaria": [
    "Veludo para Perfumaria #1",
    "Perfumaria Versão Madeira 14",
    "Sortido Perfumaria Cinza",
    "Perfumaria Versão Vidro 195",
    "Perfumaria Light 69",
    "Perfumaria Tipo Industrial 113",
    "Slim para Perfumaria #8",
    "Perfumaria Coleção Luxo 80",
    "Perfumaria Linha Recarregável 105",
    "Perfumaria Zero 30",
    "Slim para Perfumaria #166",
    "Estojo Perfumaria Doméstico",
    "Perfumaria Edição Plástico 124",
    "Artesanal para Perfumaria #117",
    "Perfumaria Tipo Cobre 49",
    "Perfumaria Sortido Eco 18",
    "Perfumaria - Plástico Colorido",
    "Perfumaria Edição Premium 73",
    "Perfumaria - Térmico Solar",
    "Retro para Perfumaria #115",
    "Perfumaria Versão Branco 86",
    "Perfumaria Sortido Prata 117",
    "Perfumaria - Adulto Natural",
    "Perfumaria Combo Orgânico 199",
    "Compacto para Perfumaria #82",
    "Prata para Perfumaria #99",
    "Estojo Perfumaria Profissional",
    "Sortido Perfumaria Térmico",
    "Perfumaria - Ultra Vidro",
    "Perfumaria Microfibra 117",
    "Perfumaria Vintage 105",
    "Conjunto Perfumaria Algodão",
    "Perfumaria - Colorido Antialérgico",
    "Reforçado para Perfumaria #85",
    "Perfumaria Combo Elegante 161",
    "Crochê para Perfumaria #10",
    "Perfumaria Modelo Natural 162",
    "Perfumaria - Orgânico Resistente",
    "Ultra para Perfumaria #195",
    "Perfumaria Vidro 43",
    "Perfumaria - Tradicional Compacto",
    "Perfumaria - Inteligente Doméstico",
    "Perfumaria - Dourado Cerâmica",
    "Pack Perfumaria Microfibra"
  ],
  "Bebês e Mamães": [
    "Bluetooth para Bebês e Mamães #175",
    "Linha Bebês e Mamães Familiar",
    "Bebês e Mamães Antiderrapante 98",
    "Bebês e Mamães Coleção Poliéster 150",
    "Pack Bebês e Mamães Couro",
    "Bebês e Mamães - Metal Importado",
    "Bebês e Mamães Couro 74",
    "Bebês e Mamães Tipo Sustentável 114",
    "Bebês e Mamães - Térmico Esportivo",
    "Importado para Bebês e Mamães #117",
    "Bebês e Mamães - Premium Gold Cobre",
    "Mini para Bebês e Mamães #61",
    "Wi-Fi para Bebês e Mamães #92",
    "Bebês e Mamães Edição Doméstico 6",
    "Gourmet para Bebês e Mamães #3",
    "Bebês e Mamães Linha Ergonômico 191",
    "Industrial para Bebês e Mamães #199",
    "Edição Bebês e Mamães Preto",
    "Modelo Bebês e Mamães Adulto",
    "Bebês e Mamães Edição Eco 161",
    "Bebês e Mamães Compacto 80",
    "Profissional para Bebês e Mamães #149",
    "Bebês e Mamães - Plus Resistente",
    "Bebês e Mamães - Rústico Plástico",
    "Pack Bebês e Mamães Plus",
    "Bebês e Mamães Kit Microfibra 129",
    "Bebês e Mamães - Econômico Importado",
    "Doméstico para Bebês e Mamães #192",
    "Bebês e Mamães - Maxi Couro",
    "Bebês e Mamães Vintage 194",
    "Tamanho Bebês e Mamães Inox",
    "Bebês e Mamães Kit Resistente 102",
    "Bebês e Mamães Nacional 138",
    "Bebês e Mamães Metal 95",
    "Bebês e Mamães - Solar Prata",
    "Bebês e Mamães - Mini Orgânico",
    "Tradicional para Bebês e Mamães #159",
    "Bebês e Mamães Kit Antiderrapante 57",
    "Bebês e Mamães Couro 180",
    "Bebês e Mamães - Madeira Maxi",
    "Kit Bebês e Mamães Profissional",
    "Bebês e Mamães - Poliéster Maxi",
    "Bebês e Mamães Natural 138",
    "Caixa Bebês e Mamães Metal"
  ],
  "Eletrônicos": [
    "Eletrônicos - Crochê Plástico",
    "Eletrônicos Tipo Plástico 168",
    "Eletrônicos Seda 158",
    "Gourmet para Eletrônicos #9",
    "Eletrônicos - Diet Vidro",
    "Natural para Eletrônicos #93",
    "Eletrônicos Dourado 140",
    "Eletrônicos - Inteligente Inox",
    "Eletrônicos - Adulto Slim",
    "Resistente para Eletrônicos #170",
    "Modelo Eletrônicos Anatômico",
    "Eletrônicos Portátil 86",
    "Linha Eletrônicos Bluetooth",
    "Conjunto Eletrônicos Recarregável",
    "Edição Eletrônicos Diet",
    "Combo Eletrônicos Vintage",
    "Eletrônicos Linha Gourmet 38",
    "Sortido Eletrônicos Importado",
    "Conjunto Eletrônicos Tradicional",
    "Kit Eletrônicos Preto",
    "Edição Eletrônicos Rústico",
    "Eletrônicos Familiar 68",
    "Eletrônicos Plus 190",
    "Microfibra para Eletrônicos #30",
    "Eletrônicos Algodão 115",
    "Eletrônicos - Veludo Térmico",
    "Eletrônicos Acrílico 129",
    "Edição Eletrônicos Compacto",
    "Eletrônicos Edição Metal 165",
    "Eletrônicos Inteligente 123",
    "Silicone para Eletrônicos #176",
    "Eletrônicos Seda 183",
    "Sustentável para Eletrônicos #21",
    "Eletrônicos - Ergonômico Vintage",
    "Eletrônicos Plus 71",
    "Eletrônicos Sortido Rústico 98",
    "Eletrônicos Sortido Doméstico 117",
    "Eletrônicos Combo Ultra 180",
    "Eletrônicos Recarregável 185",
    "Caixa Eletrônicos Acrílico",
    "Caixa Eletrônicos Colorido",
    "Bambu para Eletrônicos #107",
    "Eletrônicos Elegante 110",
    "Eletrônicos - Importado Dourado"
  ],
  "Informática": [
    "Modelo Informática Algodão",
    "Informática Resistente 22",
    "Informática Cerâmica 25",
    "Informática - Plus Sem Fio",
    "Informática Térmico 144",
    "Informática Kit Slim 106",
    "Informática - Silicone Portátil",
    "Informática - Anatômico Casual",
    "Informática - Mini Wi-Fi",
    "Informática Coleção Retro 169",
    "Zero para Informática #28",
    "Informática - Sem Fio Dourado",
    "Informática Gourmet 147",
    "Tipo Informática Silicone",
    "Informática Sortido Tradicional 156",
    "Informática - Tradicional Infantil",
    "Informática - Casual Colorido",
    "Informática - Premium Infantil",
    "Edição Informática Bambu",
    "Informática Vintage 190",
    "Informática Resistente 192",
    "Informática Coleção Prata 108",
    "Colorido para Informática #41",
    "Informática - Casual Rústico",
    "Informática Modelo Portátil 40",
    "Tipo Informática Antialérgico",
    "Informática Reforçado 70",
    "Silicone para Informática #125",
    "Informática Versão Plástico 70",
    "Tipo Informática Veludo",
    "Informática Branco 111",
    "Informática Industrial 174",
    "Informática Versão Microfibra 171",
    "Informática - Compacto Zero",
    "Anatômico para Informática #15",
    "Informática Light 78",
    "Tipo Informática Eco",
    "Informática - Doméstico Rústico",
    "Informática Premium 128",
    "Familiar para Informática #34",
    "Tricô para Informática #181",
    "Sortido Informática Sem Fio",
    "Informática - Sustentável Inox",
    "Informática Cerâmica 5"
  ],
  "Eletrodomésticos": [
    "Sustentável para Eletrodomésticos #81",
    "Eletrodomésticos Combo Wi-Fi 104",
    "Doméstico para Eletrodomésticos #30",
    "Moderno para Eletrodomésticos #84",
    "Tipo Eletrodomésticos Antialérgico",
    "Cinza para Eletrodomésticos #23",
    "Mini para Eletrodomésticos #63",
    "Térmico para Eletrodomésticos #103",
    "Eletrodomésticos Modelo Inox 80",
    "Eletrodomésticos - Zero Minimalista",
    "Conjunto Eletrodomésticos Veludo",
    "Eletrodomésticos Microfibra 131",
    "Versão Eletrodomésticos Branco",
    "Eletrodomésticos - Vintage Natural",
    "Eletrodomésticos Vintage 66",
    "Linha Eletrodomésticos Ergonômico",
    "Tipo Eletrodomésticos Sustentável",
    "Tipo Eletrodomésticos Poliéster",
    "Bluetooth para Eletrodomésticos #195",
    "Eletrodomésticos Versão Bluetooth 165",
    "Eletrodomésticos Kit Elegante 39",
    "Ecológico para Eletrodomésticos #121",
    "Esportivo para Eletrodomésticos #71",
    "Eletrodomésticos Linha Preto 130",
    "Eletrodomésticos Casual 119",
    "Profissional para Eletrodomésticos #15",
    "Eletrodomésticos - Industrial Sustentável",
    "Eletrodomésticos Antiderrapante 153",
    "Eletrodomésticos Combo Couro 149",
    "Eletrodomésticos Linha Acrílico 147",
    "Combo Eletrodomésticos Ergonômico",
    "Nylon para Eletrodomésticos #39",
    "Eletrodomésticos Acrílico 27",
    "Eletrodomésticos - Reforçado Nylon",
    "Kit Eletrodomésticos Artesanal",
    "Vidro para Eletrodomésticos #135",
    "Eletrodomésticos Tipo Cinza 96",
    "Eletrodomésticos - Cobre Madeira",
    "Eletrodomésticos - Anatômico Portátil",
    "Eletrodomésticos - Ecológico Minimalista",
    "Eletrodomésticos Sem Fio 174",
    "Industrial para Eletrodomésticos #65",
    "Eletrodomésticos Tipo Minimalista 21",
    "Eletrodomésticos Tipo Branco 80"
  ],
  "Eletroportáteis": [
    "Plus para Eletroportáteis #153",
    "Eletroportáteis Casual 144",
    "Minimalista para Eletroportáteis #33",
    "Eletroportáteis Modelo Silicone 131",
    "Eletroportáteis - Moderno Cinza",
    "Eletroportáteis - Infantil Diet",
    "Eletroportáteis - Seda Adulto",
    "Linha Eletroportáteis Retro",
    "Eletroportáteis Doméstico 26",
    "Eletroportáteis Sortido Microfibra 10",
    "Eletroportáteis - Antialérgico Plus",
    "Eletroportáteis Combo Retro 42",
    "Tamanho Eletroportáteis Antialérgico",
    "Série Eletroportáteis Vidro",
    "Eletroportáteis Madeira 94",
    "Estojo Eletroportáteis Antiderrapante",
    "Eletroportáteis - Acrílico Orgânico",
    "Eletroportáteis Coleção Casual 121",
    "Combo Eletroportáteis Wi-Fi",
    "Couro para Eletroportáteis #197",
    "Eletroportáteis - Prata Nylon",
    "Eletroportáteis Combo Luxo 52",
    "Eletroportáteis Tipo Importado 14",
    "Dourado para Eletroportáteis #142",
    "Eletroportáteis Camurça 32",
    "Eletroportáteis - Reforçado Luxo",
    "Eletroportáteis - Acrílico Veludo",
    "Tamanho Eletroportáteis Cerâmica",
    "Eletroportáteis Zero 116",
    "Eletroportáteis - Tradicional Plástico",
    "Eletroportáteis Inox 129",
    "Eletroportáteis - Natural Cobre",
    "Eletroportáteis Dourado 58",
    "Eletroportáteis Elegante 26",
    "Eletroportáteis - Vintage Eco",
    "Eletroportáteis Industrial 121",
    "Tipo Eletroportáteis Algodão",
    "Antiderrapante para Eletroportáteis #2",
    "Eletroportáteis Moderno 66",
    "Tamanho Eletroportáteis Retro",
    "Eletroportáteis Sortido Silicone 29",
    "Eletroportáteis - Natural Esportivo",
    "Eletroportáteis Portátil 62",
    "Antialérgico para Eletroportáteis #118"
  ],
  "Áudio e Vídeo": [
    "Áudio e Vídeo Maxi 128",
    "Áudio e Vídeo Sortido Moderno 162",
    "Áudio e Vídeo Coleção Vintage 75",
    "Premium para Áudio e Vídeo #158",
    "Áudio e Vídeo - Natural Wi-Fi",
    "Infantil para Áudio e Vídeo #171",
    "Áudio e Vídeo Microfibra 93",
    "Áudio e Vídeo Microfibra 140",
    "Áudio e Vídeo Sortido Recarregável 6",
    "Algodão para Áudio e Vídeo #12",
    "Dourado para Áudio e Vídeo #65",
    "Áudio e Vídeo Preto 18",
    "Áudio e Vídeo - Natural Mini",
    "Áudio e Vídeo Kit Eco 12",
    "Áudio e Vídeo - Crochê Colorido",
    "Tamanho Áudio e Vídeo Couro",
    "Infantil para Áudio e Vídeo #35",
    "Áudio e Vídeo Metal 10",
    "Áudio e Vídeo - Premium Gold Compacto",
    "Versão Áudio e Vídeo Compacto",
    "Áudio e Vídeo - Casual Veludo",
    "Crochê para Áudio e Vídeo #122",
    "Áudio e Vídeo - Profissional Adulto",
    "Áudio e Vídeo - Preto Portátil",
    "Áudio e Vídeo - Caseiro Slim",
    "Áudio e Vídeo - Cerâmica Bambu",
    "Cobre para Áudio e Vídeo #87",
    "Estojo Áudio e Vídeo Poliéster",
    "Áudio e Vídeo - Camurça Caseiro",
    "Áudio e Vídeo Silicone 21",
    "Ergonômico para Áudio e Vídeo #47",
    "Áudio e Vídeo Edição Rústico 27",
    "Áudio e Vídeo Rústico 170",
    "Áudio e Vídeo - Casual Acrílico",
    "Áudio e Vídeo Combo Econômico 177",
    "Branco para Áudio e Vídeo #115",
    "Áudio e Vídeo Preto 158",
    "Gourmet para Áudio e Vídeo #164",
    "Áudio e Vídeo Sustentável 172",
    "Cinza para Áudio e Vídeo #132",
    "Kit Áudio e Vídeo Vintage",
    "Áudio e Vídeo Versão Profissional 33",
    "Áudio e Vídeo Natural 166",
    "Áudio e Vídeo - Cinza Cobre"
  ],
  "Telefonia e Celulares": [
    "Telefonia e Celulares Linha Ergonômico 40",
    "Dourado para Telefonia e Celulares #96",
    "Sustentável para Telefonia e Celulares #147",
    "Sortido Telefonia e Celulares Cinza",
    "Elegante para Telefonia e Celulares #167",
    "Telefonia e Celulares - Artesanal Maxi",
    "Telefonia e Celulares Infantil 128",
    "Telefonia e Celulares Combo Sem Fio 31",
    "Telefonia e Celulares - Nacional Acrílico",
    "Edição Telefonia e Celulares Industrial",
    "Premium Gold para Telefonia e Celulares #32",
    "Tamanho Telefonia e Celulares Sustentável",
    "Familiar para Telefonia e Celulares #183",
    "Resistente para Telefonia e Celulares #175",
    "Telefonia e Celulares - Branco Ecológico",
    "Telefonia e Celulares Sortido Doméstico 77",
    "Série Telefonia e Celulares Familiar",
    "Telefonia e Celulares - Veludo Zero",
    "Telefonia e Celulares Premium Gold 36",
    "Tipo Telefonia e Celulares Poliéster",
    "Telefonia e Celulares Cinza 142",
    "Telefonia e Celulares Kit Couro 142",
    "Edição Telefonia e Celulares Resistente",
    "Telefonia e Celulares Casual 102",
    "Microfibra para Telefonia e Celulares #106",
    "Wi-Fi para Telefonia e Celulares #19",
    "Combo Telefonia e Celulares Sustentável",
    "Couro para Telefonia e Celulares #175",
    "Telefonia e Celulares Kit Plus 142",
    "Telefonia e Celulares Tipo Plus 111",
    "Telefonia e Celulares Linha Slim 133",
    "Coleção Telefonia e Celulares Econômico",
    "Combo Telefonia e Celulares Zero",
    "Telefonia e Celulares - Camurça Industrial",
    "Telefonia e Celulares Importado 51",
    "Telefonia e Celulares Edição Plus 161",
    "Telefonia e Celulares - Antiderrapante Tricô",
    "Telefonia e Celulares Nylon 165",
    "Edição Telefonia e Celulares Solar",
    "Linha Telefonia e Celulares Antialérgico",
    "Telefonia e Celulares Kit Bluetooth 11",
    "Telefonia e Celulares Reforçado 12",
    "Telefonia e Celulares Edição Light 197",
    "Telefonia e Celulares Combo Antialérgico 164"
  ],
  "Games e Consoles": [
    "Games e Consoles Poliéster 161",
    "Games e Consoles Edição Esportivo 124",
    "Tipo Games e Consoles Bambu",
    "Games e Consoles - Metal Sustentável",
    "Games e Consoles Luxo 113",
    "Linho para Games e Consoles #119",
    "Combo Games e Consoles Ergonômico",
    "Combo Games e Consoles Elegante",
    "Games e Consoles - Bambu Plus",
    "Games e Consoles - Veludo Sem Fio",
    "Games e Consoles Elegante 62",
    "Slim para Games e Consoles #69",
    "Artesanal para Games e Consoles #37",
    "Games e Consoles Portátil 75",
    "Antiderrapante para Games e Consoles #108",
    "Tamanho Games e Consoles Luxo",
    "Games e Consoles - Wi-Fi Elegante",
    "Tipo Games e Consoles Luxo",
    "Veludo para Games e Consoles #120",
    "Casual para Games e Consoles #128",
    "Games e Consoles Resistente 101",
    "Games e Consoles Versão Natural 56",
    "Games e Consoles Kit Portátil 13",
    "Games e Consoles - Poliéster Anatômico",
    "Industrial para Games e Consoles #138",
    "Games e Consoles Mini 111",
    "Versão Games e Consoles Nacional",
    "Games e Consoles - Bambu Cinza",
    "Games e Consoles Bambu 14",
    "Games e Consoles Sortido Adulto 93",
    "Games e Consoles Edição Sustentável 99",
    "Games e Consoles Versão Recarregável 72",
    "Games e Consoles Modelo Plus 25",
    "Dourado para Games e Consoles #87",
    "Games e Consoles Kit Vintage 51",
    "Games e Consoles Sortido Bambu 129",
    "Games e Consoles Compacto 10",
    "Série Games e Consoles Minimalista",
    "Camurça para Games e Consoles #117",
    "Edição Games e Consoles Veludo",
    "Combo Games e Consoles Antiderrapante",
    "Games e Consoles - Luxo Inox",
    "Games e Consoles Edição Térmico 87",
    "Games e Consoles Sortido Tricô 126"
  ],
  "Móveis": [
    "Móveis Edição Algodão 5",
    "Móveis - Minimalista Maxi",
    "Solar para Móveis #79",
    "Móveis Anatômico 122",
    "Móveis - Solar Wi-Fi",
    "Série Móveis Portátil",
    "Móveis Versão Econômico 135",
    "Móveis Combo Vintage 175",
    "Kit Móveis Wi-Fi",
    "Móveis Adulto 5",
    "Elegante para Móveis #108",
    "Caixa Móveis Light",
    "Nylon para Móveis #199",
    "Móveis Versão Inteligente 181",
    "Sortido Móveis Light",
    "Móveis Kit Linho 135",
    "Elegante para Móveis #45",
    "Tricô para Móveis #88",
    "Móveis Kit Nacional 157",
    "Adulto para Móveis #64",
    "Móveis - Sem Fio Esportivo",
    "Coleção Móveis Industrial",
    "Série Móveis Seda",
    "Móveis - Linho Branco",
    "Móveis Edição Industrial 32",
    "Móveis Sortido Prata 102",
    "Móveis - Vintage Doméstico",
    "Móveis Industrial 183",
    "Móveis Branco 114",
    "Móveis - Linho Diet",
    "Tamanho Móveis Tricô",
    "Móveis - Sem Fio Caseiro",
    "Conjunto Móveis Antiderrapante",
    "Móveis Coleção Artesanal 13",
    "Móveis Coleção Orgânico 14",
    "Móveis Madeira 85",
    "Ultra para Móveis #175",
    "Kit Móveis Recarregável",
    "Caixa Móveis Algodão",
    "Premium Gold para Móveis #194",
    "Móveis - Rústico Industrial",
    "Móveis Resistente 167",
    "Móveis Coleção Tricô 190",
    "Móveis Familiar 107"
  ],
  "Decoração": [
    "Versão Decoração Profissional",
    "Poliéster para Decoração #48",
    "Decoração - Profissional Clássico",
    "Decoração - Bluetooth Ergonômico",
    "Decoração Minimalista 73",
    "Crochê para Decoração #135",
    "Eco para Decoração #130",
    "Caseiro para Decoração #50",
    "Decoração Minimalista 42",
    "Importado para Decoração #184",
    "Kit Decoração Colorido",
    "Decoração - Bluetooth Adulto",
    "Edição Decoração Bambu",
    "Veludo para Decoração #84",
    "Decoração Bambu 172",
    "Decoração Infantil 36",
    "Rústico para Decoração #64",
    "Decoração Nacional 99",
    "Estojo Decoração Caseiro",
    "Decoração - Esportivo Solar",
    "Decoração Linha Nacional 168",
    "Decoração - Natural Inteligente",
    "Decoração Couro 79",
    "Caixa Decoração Nylon",
    "Decoração - Slim Doméstico",
    "Decoração - Antiderrapante Zero",
    "Linha Decoração Linho",
    "Estojo Decoração Ergonômico",
    "Decoração - Plástico Recarregável",
    "Tricô para Decoração #171",
    "Tipo Decoração Artesanal",
    "Decoração Modelo Microfibra 115",
    "Decoração Kit Sustentável 145",
    "Decoração Inteligente 141",
    "Decoração Coleção Wi-Fi 138",
    "Linha Decoração Rústico",
    "Decoração Versão Maxi 175",
    "Série Decoração Solar",
    "Resistente para Decoração #131",
    "Inteligente para Decoração #117",
    "Sortido Decoração Plástico",
    "Bluetooth para Decoração #15",
    "Decoração Versão Casual 186",
    "Decoração Inox 66"
  ],
  "Cama, Mesa e Banho": [
    "Cama, Mesa e Banho Diet 149",
    "Cama, Mesa e Banho Compacto 109",
    "Cama, Mesa e Banho - Ecológico Crochê",
    "Cama, Mesa e Banho Ecológico 121",
    "Cama, Mesa e Banho Industrial 105",
    "Tipo Cama, Mesa e Banho Eco",
    "Dourado para Cama, Mesa e Banho #98",
    "Prata para Cama, Mesa e Banho #97",
    "Cama, Mesa e Banho Crochê 35",
    "Cama, Mesa e Banho - Slim Familiar",
    "Cama, Mesa e Banho Combo Microfibra 33",
    "Tamanho Cama, Mesa e Banho Premium",
    "Cama, Mesa e Banho Esportivo 119",
    "Cama, Mesa e Banho Combo Tricô 98",
    "Pack Cama, Mesa e Banho Metal",
    "Cama, Mesa e Banho - Retro Gourmet",
    "Versão Cama, Mesa e Banho Maxi",
    "Cama, Mesa e Banho Plástico 158",
    "Cama, Mesa e Banho Natural 53",
    "Cama, Mesa e Banho Ultra 153",
    "Cama, Mesa e Banho Acrílico 154",
    "Cama, Mesa e Banho Artesanal 190",
    "Cama, Mesa e Banho Bambu 113",
    "Sortido Cama, Mesa e Banho Diet",
    "Cama, Mesa e Banho Eco 129",
    "Cama, Mesa e Banho - Orgânico Wi-Fi",
    "Cama, Mesa e Banho - Wi-Fi Anatômico",
    "Cama, Mesa e Banho - Natural Esportivo",
    "Modelo Cama, Mesa e Banho Camurça",
    "Caixa Cama, Mesa e Banho Esportivo",
    "Cama, Mesa e Banho - Inteligente Sem Fio",
    "Cama, Mesa e Banho Tipo Silicone 143",
    "Portátil para Cama, Mesa e Banho #89",
    "Microfibra para Cama, Mesa e Banho #82",
    "Madeira para Cama, Mesa e Banho #39",
    "Cama, Mesa e Banho - Prata Infantil",
    "Cama, Mesa e Banho Versão Natural 58",
    "Cama, Mesa e Banho - Vintage Couro",
    "Cama, Mesa e Banho Sem Fio 106",
    "Sem Fio para Cama, Mesa e Banho #136",
    "Caixa Cama, Mesa e Banho Artesanal",
    "Cama, Mesa e Banho - Light Minimalista",
    "Cama, Mesa e Banho Acrílico 95",
    "Cama, Mesa e Banho Tricô 186"
  ],
  "Utilidades Domésticas": [
    "Kit Utilidades Domésticas Caseiro",
    "Ergonômico para Utilidades Domésticas #155",
    "Utilidades Domésticas Sustentável 49",
    "Utilidades Domésticas Sortido Diet 123",
    "Tamanho Utilidades Domésticas Minimalista",
    "Utilidades Domésticas - Clássico Diet",
    "Série Utilidades Domésticas Slim",
    "Artesanal para Utilidades Domésticas #179",
    "Utilidades Domésticas Coleção Inox 62",
    "Utilidades Domésticas Kit Industrial 98",
    "Tricô para Utilidades Domésticas #167",
    "Utilidades Domésticas - Casual Nacional",
    "Utilidades Domésticas - Veludo Poliéster",
    "Ultra para Utilidades Domésticas #185",
    "Elegante para Utilidades Domésticas #53",
    "Utilidades Domésticas - Elegante Madeira",
    "Utilidades Domésticas Bluetooth 57",
    "Kit Utilidades Domésticas Nacional",
    "Utilidades Domésticas Combo Doméstico 40",
    "Combo Utilidades Domésticas Orgânico",
    "Bluetooth para Utilidades Domésticas #63",
    "Recarregável para Utilidades Domésticas #168",
    "Utilidades Domésticas - Importado Seda",
    "Metal para Utilidades Domésticas #44",
    "Utilidades Domésticas - Econômico Eco",
    "Utilidades Domésticas Versão Infantil 139",
    "Utilidades Domésticas Microfibra 9",
    "Utilidades Domésticas Portátil 196",
    "Utilidades Domésticas Madeira 36",
    "Conjunto Utilidades Domésticas Retro",
    "Utilidades Domésticas Diet 130",
    "Dourado para Utilidades Domésticas #16",
    "Utilidades Domésticas Versão Seda 5",
    "Utilidades Domésticas Tricô 142",
    "Clássico para Utilidades Domésticas #5",
    "Utilidades Domésticas Edição Tricô 74",
    "Utilidades Domésticas Nylon 179",
    "Familiar para Utilidades Domésticas #28",
    "Utilidades Domésticas Microfibra 39",
    "Pack Utilidades Domésticas Antialérgico",
    "Utilidades Domésticas Edição Preto 69",
    "Reforçado para Utilidades Domésticas #96",
    "Metal para Utilidades Domésticas #145",
    "Série Utilidades Domésticas Zero"
  ],
  "Cozinha": [
    "Cozinha - Reforçado Profissional",
    "Cozinha Bambu 98",
    "Recarregável para Cozinha #122",
    "Cozinha Clássico 180",
    "Conjunto Cozinha Poliéster",
    "Minimalista para Cozinha #145",
    "Cozinha Microfibra 11",
    "Pack Cozinha Bluetooth",
    "Caseiro para Cozinha #12",
    "Cozinha Gourmet 140",
    "Cozinha Linha Familiar 81",
    "Cozinha Light 151",
    "Tipo Cozinha Inox",
    "Cozinha Esportivo 42",
    "Cozinha Coleção Bluetooth 100",
    "Cozinha Kit Cobre 194",
    "Tipo Cozinha Reforçado",
    "Cozinha Kit Portátil 26",
    "Orgânico para Cozinha #20",
    "Cozinha - Ergonômico Antiderrapante",
    "Cozinha Combo Rústico 8",
    "Cozinha - Acrílico Seda",
    "Combo Cozinha Recarregável",
    "Cerâmica para Cozinha #48",
    "Cozinha Combo Reforçado 198",
    "Cozinha Edição Artesanal 183",
    "Cozinha Reforçado 69",
    "Caixa Cozinha Retro",
    "Elegante para Cozinha #93",
    "Cozinha Resistente 2",
    "Cozinha - Vidro Cinza",
    "Cozinha - Mini Plus",
    "Cozinha Infantil 111",
    "Sem Fio para Cozinha #143",
    "Cozinha Combo Mini 7",
    "Cozinha Preto 142",
    "Cozinha Anatômico 154",
    "Cozinha - Cobre Clássico",
    "Cozinha - Madeira Cobre",
    "Cozinha Sem Fio 63",
    "Cozinha Sortido Econômico 176",
    "Econômico para Cozinha #36",
    "Cozinha - Esportivo Caseiro",
    "Vintage para Cozinha #17"
  ],
  "Organização e Arrumação": [
    "Caixa Organização e Arrumação Gourmet",
    "Esportivo para Organização e Arrumação #124",
    "Organização e Arrumação Cinza 65",
    "Série Organização e Arrumação Poliéster",
    "Organização e Arrumação Coleção Metal 28",
    "Coleção Organização e Arrumação Premium",
    "Minimalista para Organização e Arrumação #159",
    "Minimalista para Organização e Arrumação #113",
    "Organização e Arrumação - Cerâmica Anatômico",
    "Coleção Organização e Arrumação Rústico",
    "Organização e Arrumação Coleção Linho 81",
    "Caixa Organização e Arrumação Elegante",
    "Organização e Arrumação - Seda Wi-Fi",
    "Combo Organização e Arrumação Prata",
    "Organização e Arrumação - Inox Cinza",
    "Organização e Arrumação Bluetooth 52",
    "Organização e Arrumação Sortido Infantil 175",
    "Organização e Arrumação Linha Couro 182",
    "Estojo Organização e Arrumação Doméstico",
    "Organização e Arrumação Madeira 173",
    "Eco para Organização e Arrumação #163",
    "Organização e Arrumação - Natural Importado",
    "Série Organização e Arrumação Silicone",
    "Sustentável para Organização e Arrumação #115",
    "Organização e Arrumação Versão Solar 103",
    "Organização e Arrumação Sortido Plástico 140",
    "Organização e Arrumação Cinza 180",
    "Organização e Arrumação Modelo Mini 197",
    "Modelo Organização e Arrumação Preto",
    "Modelo Organização e Arrumação Antiderrapante",
    "Organização e Arrumação Bluetooth 166",
    "Minimalista para Organização e Arrumação #111",
    "Organização e Arrumação Clássico 26",
    "Organização e Arrumação - Zero Veludo",
    "Organização e Arrumação Sortido Solar 177",
    "Organização e Arrumação Coleção Acrílico 96",
    "Couro para Organização e Arrumação #198",
    "Organização e Arrumação Sortido Retro 89",
    "Organização e Arrumação Linho 27",
    "Organização e Arrumação - Plástico Reforçado",
    "Organização e Arrumação Vintage 90",
    "Organização e Arrumação - Colorido Metal",
    "Sortido Organização e Arrumação Linho",
    "Organização e Arrumação - Algodão Ultra"
  ],
  "Iluminação": [
    "Acrílico para Iluminação #82",
    "Iluminação Esportivo 12",
    "Iluminação Moderno 88",
    "Iluminação Econômico 190",
    "Sortido Iluminação Familiar",
    "Iluminação Tipo Minimalista 144",
    "Couro para Iluminação #60",
    "Infantil para Iluminação #48",
    "Inox para Iluminação #8",
    "Iluminação Coleção Acrílico 152",
    "Cobre para Iluminação #2",
    "Pack Iluminação Gourmet",
    "Iluminação Wi-Fi 27",
    "Iluminação Tipo Cinza 84",
    "Estojo Iluminação Maxi",
    "Iluminação - Seda Microfibra",
    "Iluminação - Anatômico Cobre",
    "Iluminação Combo Térmico 30",
    "Iluminação - Preto Metal",
    "Iluminação Tipo Esportivo 158",
    "Iluminação Modelo Eco 81",
    "Iluminação Natural 79",
    "Iluminação Infantil 96",
    "Sortido Iluminação Cobre",
    "Anatômico para Iluminação #36",
    "Iluminação Combo Silicone 48",
    "Tricô para Iluminação #178",
    "Sortido Iluminação Econômico",
    "Industrial para Iluminação #36",
    "Combo Iluminação Acrílico",
    "Iluminação Linha Preto 3",
    "Eco para Iluminação #50",
    "Sem Fio para Iluminação #130",
    "Madeira para Iluminação #176",
    "Plástico para Iluminação #182",
    "Seda para Iluminação #43",
    "Iluminação Bluetooth 8",
    "Coleção Iluminação Profissional",
    "Iluminação - Zero Tricô",
    "Iluminação - Econômico Metal",
    "Iluminação Versão Recarregável 131",
    "Iluminação Wi-Fi 30",
    "Iluminação - Crochê Cinza",
    "Iluminação Linha Vidro 140"
  ],
  "Moda Feminina": [
    "Caixa Moda Feminina Mini",
    "Coleção Moda Feminina Profissional",
    "Nacional para Moda Feminina #90",
    "Moda Feminina Vidro 31",
    "Pack Moda Feminina Térmico",
    "Moda Feminina - Antiderrapante Silicone",
    "Edição Moda Feminina Eco",
    "Tamanho Moda Feminina Light",
    "Moda Feminina Bluetooth 90",
    "Moda Feminina Edição Anatômico 138",
    "Combo Moda Feminina Doméstico",
    "Moda Feminina - Wi-Fi Caseiro",
    "Moda Feminina Modelo Eco 193",
    "Inteligente para Moda Feminina #71",
    "Série Moda Feminina Plus",
    "Linha Moda Feminina Rústico",
    "Tipo Moda Feminina Inox",
    "Vintage para Moda Feminina #148",
    "Moda Feminina - Plástico Prata",
    "Sustentável para Moda Feminina #163",
    "Moda Feminina Bambu 132",
    "Moda Feminina - Dourado Metal",
    "Rústico para Moda Feminina #149",
    "Moda Feminina Resistente 188",
    "Preto para Moda Feminina #17",
    "Moda Feminina Combo Diet 110",
    "Estojo Moda Feminina Caseiro",
    "Moda Feminina - Industrial Colorido",
    "Moda Feminina Tipo Bluetooth 125",
    "Moda Feminina - Portátil Compacto",
    "Moda Feminina Metal 5",
    "Moda Feminina Luxo 113",
    "Premium para Moda Feminina #110",
    "Moda Feminina - Luxo Gourmet",
    "Moda Feminina Cinza 65",
    "Moda Feminina Dourado 171",
    "Kit Moda Feminina Inox",
    "Moda Feminina - Orgânico Silicone",
    "Moda Feminina Ultra 1",
    "Estojo Moda Feminina Sustentável",
    "Edição Moda Feminina Zero",
    "Moda Feminina Versão Clássico 3",
    "Moda Feminina - Slim Silicone",
    "Caixa Moda Feminina Resistente"
  ],
  "Moda Masculina": [
    "Moda Masculina Mini 81",
    "Moda Masculina - Esportivo Eco",
    "Eco para Moda Masculina #165",
    "Conjunto Moda Masculina Microfibra",
    "Moda Masculina Linha Antiderrapante 167",
    "Estojo Moda Masculina Branco",
    "Modelo Moda Masculina Retro",
    "Antiderrapante para Moda Masculina #176",
    "Diet para Moda Masculina #23",
    "Moda Masculina Eco 193",
    "Moda Masculina Térmico 187",
    "Branco para Moda Masculina #110",
    "Moda Masculina - Eco Artesanal",
    "Moda Masculina - Reforçado Artesanal",
    "Moda Masculina Edição Tradicional 169",
    "Moda Masculina - Light Camurça",
    "Moda Masculina Sortido Adulto 192",
    "Doméstico para Moda Masculina #166",
    "Moda Masculina Natural 127",
    "Maxi para Moda Masculina #62",
    "Anatômico para Moda Masculina #19",
    "Moda Masculina Linha Cinza 82",
    "Caixa Moda Masculina Bluetooth",
    "Cinza para Moda Masculina #140",
    "Tipo Moda Masculina Algodão",
    "Moda Masculina Moderno 151",
    "Moda Masculina Clássico 68",
    "Kit Moda Masculina Inteligente",
    "Nylon para Moda Masculina #74",
    "Moda Masculina Combo Silicone 180",
    "Reforçado para Moda Masculina #164",
    "Moda Masculina Sortido Antiderrapante 40",
    "Moda Masculina - Reforçado Casual",
    "Moda Masculina Veludo 53",
    "Sortido Moda Masculina Rústico",
    "Térmico para Moda Masculina #163",
    "Moda Masculina Casual 179",
    "Natural para Moda Masculina #15",
    "Conjunto Moda Masculina Cerâmica",
    "Moda Masculina Metal 157",
    "Moda Masculina Linha Casual 171",
    "Conjunto Moda Masculina Clássico",
    "Série Moda Masculina Clássico",
    "Moda Masculina Sortido Nacional 43"
  ],
  "Moda Infantil": [
    "Moda Infantil - Plus Caseiro",
    "Moda Infantil Tradicional 86",
    "Caseiro para Moda Infantil #135",
    "Moda Infantil Nacional 183",
    "Moda Infantil Modelo Poliéster 117",
    "Moda Infantil Kit Inteligente 128",
    "Moda Infantil Tipo Dourado 41",
    "Moda Infantil - Mini Wi-Fi",
    "Moda Infantil Orgânico 190",
    "Moda Infantil Linha Compacto 4",
    "Kit Moda Infantil Algodão",
    "Moda Infantil - Cobre Retro",
    "Versão Moda Infantil Profissional",
    "Moda Infantil Combo Zero 83",
    "Caixa Moda Infantil Elegante",
    "Moda Infantil - Sustentável Wi-Fi",
    "Moda Infantil - Slim Nylon",
    "Moda Infantil Familiar 58",
    "Moda Infantil Linha Bambu 18",
    "Industrial para Moda Infantil #199",
    "Moda Infantil - Rústico Resistente",
    "Moda Infantil Versão Clássico 95",
    "Coleção Moda Infantil Bluetooth",
    "Moda Infantil - Antialérgico Artesanal",
    "Dourado para Moda Infantil #152",
    "Premium Gold para Moda Infantil #188",
    "Moda Infantil Coleção Retro 2",
    "Tradicional para Moda Infantil #60",
    "Moda Infantil Kit Clássico 86",
    "Moda Infantil Prata 189",
    "Moda Infantil - Mini Light",
    "Moda Infantil Coleção Plástico 126",
    "Moda Infantil Vintage 183",
    "Moda Infantil - Resistente Compacto",
    "Versão Moda Infantil Camurça",
    "Dourado para Moda Infantil #118",
    "Moda Infantil Solar 25",
    "Moda Infantil Tipo Inox 20",
    "Moda Infantil Linha Cerâmica 170",
    "Pack Moda Infantil Doméstico",
    "Moda Infantil - Elegante Inox",
    "Moda Infantil - Elegante Acrílico",
    "Moda Infantil - Orgânico Sustentável",
    "Linha Moda Infantil Solar"
  ],
  "Moda Praia": [
    "Moda Praia Retro 28",
    "Estojo Moda Praia Couro",
    "Moda Praia - Madeira Slim",
    "Moda Praia Kit Light 116",
    "Moda Praia - Couro Nacional",
    "Moda Praia Resistente 41",
    "Moda Praia - Ergonômico Compacto",
    "Tamanho Moda Praia Rústico",
    "Conjunto Moda Praia Artesanal",
    "Moda Praia - Inox Veludo",
    "Moda Praia Esportivo 67",
    "Kit Moda Praia Bambu",
    "Sem Fio para Moda Praia #192",
    "Moda Praia Coleção Ultra 119",
    "Moda Praia Eco 32",
    "Moda Praia Inteligente 57",
    "Pack Moda Praia Bambu",
    "Moda Praia - Reforçado Solar",
    "Moda Praia Edição Sustentável 6",
    "Moda Praia Premium Gold 166",
    "Plus para Moda Praia #24",
    "Moda Praia - Slim Compacto",
    "Portátil para Moda Praia #44",
    "Moda Praia Combo Inox 128",
    "Moda Praia Prata 175",
    "Familiar para Moda Praia #91",
    "Versão Moda Praia Infantil",
    "Moda Praia - Gourmet Acrílico",
    "Kit Moda Praia Antiderrapante",
    "Moda Praia Coleção Doméstico 128",
    "Recarregável para Moda Praia #123",
    "Moda Praia Resistente 72",
    "Eco para Moda Praia #108",
    "Modelo Moda Praia Microfibra",
    "Modelo Moda Praia Crochê",
    "Moda Praia Prata 183",
    "Moda Praia - Linho Crochê",
    "Branco para Moda Praia #145",
    "Moda Praia Kit Cobre 70",
    "Kit Moda Praia Elegante",
    "Moda Praia Coleção Tradicional 72",
    "Moda Praia Algodão 136",
    "Moda Praia - Solar Orgânico",
    "Coleção Moda Praia Tricô"
  ],
  "Moda Fitness": [
    "Moda Fitness Zero 148",
    "Preto para Moda Fitness #45",
    "Pack Moda Fitness Térmico",
    "Moda Fitness - Preto Térmico",
    "Moda Fitness Preto 146",
    "Moda Fitness Tipo Bluetooth 49",
    "Crochê para Moda Fitness #80",
    "Estojo Moda Fitness Profissional",
    "Moda Fitness Inteligente 60",
    "Moda Fitness Coleção Moderno 135",
    "Premium para Moda Fitness #85",
    "Moda Fitness Coleção Plus 88",
    "Versão Moda Fitness Rústico",
    "Moda Fitness Moderno 38",
    "Moda Fitness Tipo Maxi 135",
    "Moda Fitness - Sustentável Dourado",
    "Térmico para Moda Fitness #26",
    "Moda Fitness - Esportivo Rústico",
    "Linha Moda Fitness Cerâmica",
    "Elegante para Moda Fitness #45",
    "Moda Fitness Kit Zero 171",
    "Moda Fitness Tipo Prata 79",
    "Moda Fitness - Plus Familiar",
    "Moda Fitness Wi-Fi 101",
    "Moda Fitness Linha Infantil 155",
    "Moda Fitness - Antiderrapante Zero",
    "Moda Fitness Modelo Poliéster 37",
    "Moda Fitness - Sustentável Natural",
    "Moda Fitness - Elegante Econômico",
    "Moda Fitness Minimalista 115",
    "Moda Fitness Nacional 54",
    "Série Moda Fitness Ecológico",
    "Moda Fitness - Importado Mini",
    "Moda Fitness Portátil 99",
    "Plástico para Moda Fitness #43",
    "Poliéster para Moda Fitness #97",
    "Moda Fitness - Crochê Prata",
    "Moda Fitness Linho 148",
    "Linha Moda Fitness Acrílico",
    "Moda Fitness Profissional 76",
    "Moda Fitness Elegante 67",
    "Moda Fitness Sustentável 88",
    "Versão Moda Fitness Prata",
    "Série Moda Fitness Sustentável"
  ],
  "Moda Íntima": [
    "Moda Íntima Modelo Colorido 153",
    "Moda Íntima Versão Tradicional 111",
    "Edição Moda Íntima Cerâmica",
    "Kit Moda Íntima Ultra",
    "Moda Íntima - Light Adulto",
    "Recarregável para Moda Íntima #185",
    "Moda Íntima Edição Industrial 77",
    "Conjunto Moda Íntima Portátil",
    "Wi-Fi para Moda Íntima #141",
    "Retro para Moda Íntima #14",
    "Moda Íntima - Premium Silicone",
    "Moda Íntima Doméstico 170",
    "Moda Íntima Versão Premium Gold 25",
    "Moda Íntima Light 44",
    "Moda Íntima - Reforçado Algodão",
    "Moda Íntima Casual 102",
    "Seda para Moda Íntima #170",
    "Moda Íntima - Resistente Crochê",
    "Infantil para Moda Íntima #95",
    "Dourado para Moda Íntima #48",
    "Compacto para Moda Íntima #68",
    "Couro para Moda Íntima #68",
    "Tamanho Moda Íntima Caseiro",
    "Moda Íntima Linha Retro 193",
    "Moda Íntima Reforçado 172",
    "Moda Íntima - Crochê Madeira",
    "Moda Íntima Coleção Recarregável 16",
    "Camurça para Moda Íntima #108",
    "Moda Íntima Versão Wi-Fi 61",
    "Esportivo para Moda Íntima #21",
    "Profissional para Moda Íntima #129",
    "Moda Íntima Sortido Wi-Fi 174",
    "Moda Íntima Tipo Slim 194",
    "Familiar para Moda Íntima #43",
    "Tipo Moda Íntima Adulto",
    "Kit Moda Íntima Silicone",
    "Moda Íntima Cerâmica 52",
    "Tamanho Moda Íntima Anatômico",
    "Moda Íntima - Elegante Ecológico",
    "Moda Íntima Cobre 143",
    "Recarregável para Moda Íntima #84",
    "Moda Íntima - Camurça Metal",
    "Moda Íntima Antialérgico 151",
    "Moda Íntima Combo Maxi 107"
  ],
  "Calçados": [
    "Linha Calçados Bluetooth",
    "Calçados Modelo Mini 145",
    "Calçados Industrial 138",
    "Calçados - Madeira Nacional",
    "Seda para Calçados #147",
    "Calçados Versão Profissional 45",
    "Calçados - Bambu Vintage",
    "Calçados Combo Profissional 102",
    "Calçados - Natural Portátil",
    "Caseiro para Calçados #96",
    "Calçados Colorido 78",
    "Calçados - Gourmet Seda",
    "Calçados Orgânico 35",
    "Calçados - Vidro Rústico",
    "Calçados - Plástico Ergonômico",
    "Calçados Adulto 114",
    "Versão Calçados Madeira",
    "Camurça para Calçados #96",
    "Calçados Veludo 41",
    "Calçados Casual 182",
    "Calçados Combo Eco 135",
    "Calçados Linha Familiar 50",
    "Tamanho Calçados Inteligente",
    "Kit Calçados Metal",
    "Calçados Cinza 181",
    "Coleção Calçados Dourado",
    "Nylon para Calçados #102",
    "Calçados Tradicional 62",
    "Calçados - Seda Anatômico",
    "Familiar para Calçados #122",
    "Calçados Sortido Branco 89",
    "Tamanho Calçados Nacional",
    "Calçados Industrial 8",
    "Portátil para Calçados #42",
    "Calçados Coleção Zero 166",
    "Modelo Calçados Light",
    "Calçados - Madeira Veludo",
    "Calçados Clássico 122",
    "Modelo Calçados Familiar",
    "Calçados Linha Zero 65",
    "Calçados Edição Gourmet 109",
    "Branco para Calçados #118",
    "Calçados - Diet Couro",
    "Calçados - Camurça Antialérgico"
  ],
  "Bolsas e Acessórios": [
    "Solar para Bolsas e Acessórios #27",
    "Bolsas e Acessórios Veludo 170",
    "Bolsas e Acessórios - Sem Fio Anatômico",
    "Bolsas e Acessórios Edição Esportivo 176",
    "Bolsas e Acessórios Linho 17",
    "Bolsas e Acessórios - Gourmet Rústico",
    "Bolsas e Acessórios - Nacional Esportivo",
    "Linha Bolsas e Acessórios Camurça",
    "Versão Bolsas e Acessórios Inteligente",
    "Bolsas e Acessórios Combo Elegante 175",
    "Série Bolsas e Acessórios Tradicional",
    "Doméstico para Bolsas e Acessórios #67",
    "Bambu para Bolsas e Acessórios #100",
    "Bolsas e Acessórios Solar 182",
    "Bolsas e Acessórios Coleção Colorido 186",
    "Modelo Bolsas e Acessórios Tricô",
    "Preto para Bolsas e Acessórios #130",
    "Bolsas e Acessórios - Econômico Sem Fio",
    "Coleção Bolsas e Acessórios Ultra",
    "Plus para Bolsas e Acessórios #190",
    "Bolsas e Acessórios - Sem Fio Infantil",
    "Bolsas e Acessórios - Resistente Zero",
    "Bolsas e Acessórios - Zero Casual",
    "Minimalista para Bolsas e Acessórios #96",
    "Bolsas e Acessórios - Solar Doméstico",
    "Slim para Bolsas e Acessórios #121",
    "Bolsas e Acessórios Solar 149",
    "Bolsas e Acessórios Modelo Algodão 50",
    "Bolsas e Acessórios Modelo Prata 136",
    "Bolsas e Acessórios - Madeira Portátil",
    "Linha Bolsas e Acessórios Premium Gold",
    "Bolsas e Acessórios - Madeira Bluetooth",
    "Vintage para Bolsas e Acessórios #81",
    "Tipo Bolsas e Acessórios Reforçado",
    "Minimalista para Bolsas e Acessórios #162",
    "Combo Bolsas e Acessórios Inteligente",
    "Bolsas e Acessórios Acrílico 71",
    "Tipo Bolsas e Acessórios Econômico",
    "Bolsas e Acessórios Tipo Seda 196",
    "Bolsas e Acessórios Plus 158",
    "Silicone para Bolsas e Acessórios #104",
    "Linho para Bolsas e Acessórios #99",
    "Bolsas e Acessórios Profissional 137",
    "Série Bolsas e Acessórios Dourado"
  ],
  "Joias e Relógios": [
    "Joias e Relógios Rústico 194",
    "Joias e Relógios Coleção Moderno 174",
    "Joias e Relógios Artesanal 58",
    "Joias e Relógios - Casual Plus",
    "Joias e Relógios Cobre 129",
    "Joias e Relógios Edição Econômico 17",
    "Joias e Relógios Esportivo 75",
    "Camurça para Joias e Relógios #153",
    "Joias e Relógios Kit Cerâmica 176",
    "Combo Joias e Relógios Seda",
    "Joias e Relógios - Adulto Econômico",
    "Moderno para Joias e Relógios #59",
    "Série Joias e Relógios Plus",
    "Série Joias e Relógios Moderno",
    "Joias e Relógios Sortido Econômico 32",
    "Joias e Relógios - Profissional Prata",
    "Joias e Relógios - Tricô Antialérgico",
    "Joias e Relógios Anatômico 13",
    "Joias e Relógios Moderno 13",
    "Joias e Relógios Plástico 114",
    "Slim para Joias e Relógios #141",
    "Joias e Relógios - Algodão Retro",
    "Série Joias e Relógios Clássico",
    "Joias e Relógios - Plástico Ultra",
    "Joias e Relógios Edição Antialérgico 156",
    "Caixa Joias e Relógios Mini",
    "Joias e Relógios Modelo Industrial 30",
    "Joias e Relógios Poliéster 51",
    "Joias e Relógios Coleção Nacional 134",
    "Combo Joias e Relógios Madeira",
    "Joias e Relógios - Luxo Compacto",
    "Joias e Relógios Versão Light 177",
    "Minimalista para Joias e Relógios #61",
    "Joias e Relógios Clássico 172",
    "Joias e Relógios Maxi 147",
    "Retro para Joias e Relógios #24",
    "Joias e Relógios Modelo Ultra 66",
    "Estojo Joias e Relógios Doméstico",
    "Joias e Relógios - Couro Portátil",
    "Joias e Relógios Familiar 11",
    "Joias e Relógios - Cinza Elegante",
    "Maxi para Joias e Relógios #25",
    "Joias e Relógios Clássico 36",
    "Combo Joias e Relógios Preto"
  ],
  "Óculos e Ótica": [
    "Antialérgico para Óculos e Ótica #69",
    "Óculos e Ótica Dourado 88",
    "Conjunto Óculos e Ótica Bambu",
    "Metal para Óculos e Ótica #70",
    "Linho para Óculos e Ótica #108",
    "Conjunto Óculos e Ótica Plus",
    "Óculos e Ótica Luxo 27",
    "Térmico para Óculos e Ótica #124",
    "Óculos e Ótica Versão Infantil 157",
    "Preto para Óculos e Ótica #157",
    "Óculos e Ótica Plus 124",
    "Maxi para Óculos e Ótica #106",
    "Compacto para Óculos e Ótica #17",
    "Óculos e Ótica - Elegante Clássico",
    "Óculos e Ótica Coleção Colorido 133",
    "Óculos e Ótica Modelo Cerâmica 170",
    "Estojo Óculos e Ótica Branco",
    "Retro para Óculos e Ótica #143",
    "Óculos e Ótica Linha Clássico 165",
    "Sortido Óculos e Ótica Algodão",
    "Econômico para Óculos e Ótica #20",
    "Rústico para Óculos e Ótica #62",
    "Óculos e Ótica - Gourmet Portátil",
    "Óculos e Ótica Coleção Recarregável 165",
    "Bambu para Óculos e Ótica #61",
    "Óculos e Ótica Metal 114",
    "Óculos e Ótica Versão Resistente 128",
    "Elegante para Óculos e Ótica #31",
    "Moderno para Óculos e Ótica #27",
    "Madeira para Óculos e Ótica #10",
    "Óculos e Ótica Sortido Premium 24",
    "Óculos e Ótica Edição Veludo 144",
    "Modelo Óculos e Ótica Metal",
    "Óculos e Ótica - Cinza Portátil",
    "Tamanho Óculos e Ótica Metal",
    "Óculos e Ótica - Sem Fio Antialérgico",
    "Óculos e Ótica Versão Cinza 184",
    "Maxi para Óculos e Ótica #25",
    "Kit Óculos e Ótica Colorido",
    "Óculos e Ótica - Doméstico Recarregável",
    "Óculos e Ótica Kit Mini 12",
    "Estojo Óculos e Ótica Eco",
    "Mini para Óculos e Ótica #66",
    "Óculos e Ótica Coleção Adulto 31"
  ],
  "Esporte e Lazer": [
    "Diet para Esporte e Lazer #118",
    "Série Esporte e Lazer Colorido",
    "Esporte e Lazer Plástico 12",
    "Esporte e Lazer Modelo Acrílico 118",
    "Esporte e Lazer Sortido Eco 128",
    "Esporte e Lazer Microfibra 189",
    "Esporte e Lazer Recarregável 111",
    "Esporte e Lazer Versão Veludo 46",
    "Esporte e Lazer Tipo Plus 27",
    "Anatômico para Esporte e Lazer #156",
    "Esporte e Lazer - Nylon Cobre",
    "Ergonômico para Esporte e Lazer #178",
    "Coleção Esporte e Lazer Inox",
    "Esporte e Lazer - Doméstico Acrílico",
    "Linha Esporte e Lazer Madeira",
    "Esporte e Lazer Sortido Esportivo 180",
    "Esporte e Lazer Kit Recarregável 162",
    "Pack Esporte e Lazer Light",
    "Esporte e Lazer Edição Branco 173",
    "Série Esporte e Lazer Familiar",
    "Esporte e Lazer Sortido Rústico 182",
    "Esporte e Lazer Preto 144",
    "Solar para Esporte e Lazer #147",
    "Tricô para Esporte e Lazer #74",
    "Clássico para Esporte e Lazer #134",
    "Esporte e Lazer Tradicional 98",
    "Kit Esporte e Lazer Inteligente",
    "Coleção Esporte e Lazer Luxo",
    "Esporte e Lazer - Importado Vintage",
    "Esporte e Lazer Doméstico 53",
    "Esporte e Lazer Linha Preto 116",
    "Esporte e Lazer Antiderrapante 173",
    "Esporte e Lazer Coleção Sem Fio 100",
    "Sortido Esporte e Lazer Industrial",
    "Esporte e Lazer Prata 100",
    "Elegante para Esporte e Lazer #142",
    "Esporte e Lazer Clássico 191",
    "Esporte e Lazer - Premium Gold Antialérgico",
    "Zero para Esporte e Lazer #163",
    "Esporte e Lazer - Térmico Crochê",
    "Esporte e Lazer Coleção Adulto 76",
    "Familiar para Esporte e Lazer #175",
    "Esporte e Lazer Infantil 45",
    "Esporte e Lazer Modelo Prata 11"
  ],
  "Camping e Aventura": [
    "Gourmet para Camping e Aventura #143",
    "Camping e Aventura - Plus Luxo",
    "Camping e Aventura Edição Premium 85",
    "Retro para Camping e Aventura #11",
    "Versão Camping e Aventura Rústico",
    "Camping e Aventura Linha Antiderrapante 170",
    "Camping e Aventura - Seda Wi-Fi",
    "Camping e Aventura Kit Sustentável 182",
    "Camping e Aventura - Microfibra Zero",
    "Sortido Camping e Aventura Ecológico",
    "Camping e Aventura Tipo Plástico 140",
    "Camping e Aventura Combo Resistente 90",
    "Versão Camping e Aventura Diet",
    "Camping e Aventura - Minimalista Cinza",
    "Camping e Aventura - Diet Antialérgico",
    "Camping e Aventura Versão Sem Fio 193",
    "Camping e Aventura Maxi 172",
    "Camping e Aventura - Acrílico Natural",
    "Camping e Aventura Coleção Compacto 175",
    "Camping e Aventura - Prata Maxi",
    "Importado para Camping e Aventura #139",
    "Camping e Aventura - Tradicional Camurça",
    "Camping e Aventura - Veludo Veludo",
    "Seda para Camping e Aventura #12",
    "Camping e Aventura - Adulto Rústico",
    "Camping e Aventura Modelo Ultra 43",
    "Camping e Aventura Sortido Premium 161",
    "Camping e Aventura Light 172",
    "Tamanho Camping e Aventura Silicone",
    "Camping e Aventura Light 138",
    "Sustentável para Camping e Aventura #192",
    "Kit Camping e Aventura Metal",
    "Camping e Aventura - Profissional Resistente",
    "Camping e Aventura Portátil 46",
    "Camping e Aventura - Sem Fio Sustentável",
    "Camping e Aventura Coleção Nacional 105",
    "Acrílico para Camping e Aventura #162",
    "Cerâmica para Camping e Aventura #81",
    "Camping e Aventura Cobre 173",
    "Camping e Aventura Tricô 2",
    "Camping e Aventura Modelo Solar 12",
    "Camping e Aventura Preto 129",
    "Camping e Aventura Doméstico 176",
    "Camping e Aventura - Ergonômico Resistente"
  ],
  "Ciclismo": [
    "Ciclismo - Vidro Prata",
    "Tradicional para Ciclismo #122",
    "Sortido Ciclismo Zero",
    "Série Ciclismo Inox",
    "Ciclismo Edição Vintage 77",
    "Ciclismo - Clássico Recarregável",
    "Ciclismo Tipo Slim 11",
    "Ciclismo Wi-Fi 153",
    "Tricô para Ciclismo #141",
    "Ciclismo Casual 54",
    "Ciclismo - Diet Madeira",
    "Ciclismo Tipo Luxo 48",
    "Edição Ciclismo Importado",
    "Conjunto Ciclismo Infantil",
    "Ciclismo Linha Recarregável 119",
    "Ciclismo Modelo Doméstico 172",
    "Ciclismo Importado 26",
    "Série Ciclismo Solar",
    "Minimalista para Ciclismo #92",
    "Modelo Ciclismo Natural",
    "Ciclismo Industrial 159",
    "Ciclismo Adulto 82",
    "Acrílico para Ciclismo #85",
    "Ciclismo Edição Solar 40",
    "Ciclismo Kit Elegante 110",
    "Kit Ciclismo Elegante",
    "Tipo Ciclismo Zero",
    "Gourmet para Ciclismo #93",
    "Modelo Ciclismo Minimalista",
    "Couro para Ciclismo #115",
    "Ciclismo - Casual Seda",
    "Ciclismo Modelo Familiar 166",
    "Ciclismo Modelo Gourmet 36",
    "Ciclismo Coleção Nacional 188",
    "Ciclismo Sustentável 5",
    "Ciclismo Linha Solar 149",
    "Térmico para Ciclismo #55",
    "Ciclismo Recarregável 67",
    "Ciclismo Sortido Algodão 168",
    "Combo Ciclismo Inox",
    "Versão Ciclismo Térmico",
    "Ciclismo - Eco Couro",
    "Ciclismo Sortido Resistente 102",
    "Ciclismo - Nylon Clássico"
  ],
  "Pesca e Náutica": [
    "Tamanho Pesca e Náutica Antiderrapante",
    "Tipo Pesca e Náutica Veludo",
    "Estojo Pesca e Náutica Luxo",
    "Edição Pesca e Náutica Bluetooth",
    "Série Pesca e Náutica Linho",
    "Pesca e Náutica - Compacto Zero",
    "Orgânico para Pesca e Náutica #17",
    "Pesca e Náutica - Dourado Orgânico",
    "Pesca e Náutica Light 133",
    "Pesca e Náutica - Cobre Algodão",
    "Compacto para Pesca e Náutica #11",
    "Pesca e Náutica - Mini Camurça",
    "Pesca e Náutica - Nacional Solar",
    "Pesca e Náutica Tipo Prata 168",
    "Cinza para Pesca e Náutica #151",
    "Pesca e Náutica Camurça 65",
    "Zero para Pesca e Náutica #133",
    "Preto para Pesca e Náutica #89",
    "Linho para Pesca e Náutica #155",
    "Pesca e Náutica Nylon 36",
    "Econômico para Pesca e Náutica #59",
    "Pesca e Náutica Veludo 165",
    "Pesca e Náutica - Diet Retro",
    "Linha Pesca e Náutica Cinza",
    "Pesca e Náutica Modelo Orgânico 107",
    "Pesca e Náutica - Maxi Linho",
    "Linho para Pesca e Náutica #54",
    "Pesca e Náutica Tipo Madeira 6",
    "Kit Pesca e Náutica Plus",
    "Pesca e Náutica Tipo Eco 162",
    "Pesca e Náutica Linha Wi-Fi 38",
    "Pesca e Náutica Econômico 67",
    "Sortido Pesca e Náutica Bambu",
    "Pesca e Náutica Linha Industrial 22",
    "Estojo Pesca e Náutica Ergonômico",
    "Linho para Pesca e Náutica #44",
    "Tamanho Pesca e Náutica Madeira",
    "Pesca e Náutica Tipo Solar 197",
    "Edição Pesca e Náutica Veludo",
    "Pesca e Náutica - Econômico Colorido",
    "Anatômico para Pesca e Náutica #152",
    "Pesca e Náutica Orgânico 97",
    "Plus para Pesca e Náutica #28",
    "Pesca e Náutica Premium Gold 134"
  ],
  "Brinquedos": [
    "Brinquedos Combo Retro 156",
    "Brinquedos Familiar 122",
    "Brinquedos Linha Tricô 129",
    "Brinquedos Resistente 124",
    "Versão Brinquedos Ergonômico",
    "Brinquedos Linha Cerâmica 134",
    "Dourado para Brinquedos #12",
    "Brinquedos Combo Orgânico 124",
    "Branco para Brinquedos #151",
    "Brinquedos Modelo Silicone 35",
    "Brinquedos - Linho Orgânico",
    "Brinquedos Industrial 154",
    "Brinquedos Combo Importado 49",
    "Brinquedos Premium 148",
    "Brinquedos Modelo Camurça 2",
    "Light para Brinquedos #177",
    "Brinquedos - Madeira Cinza",
    "Brinquedos Retro 110",
    "Brinquedos Edição Nacional 138",
    "Bluetooth para Brinquedos #94",
    "Brinquedos Edição Inox 194",
    "Caixa Brinquedos Recarregável",
    "Brinquedos Versão Familiar 95",
    "Brinquedos Sortido Linho 65",
    "Brinquedos - Wi-Fi Branco",
    "Eco para Brinquedos #169",
    "Brinquedos Orgânico 115",
    "Conjunto Brinquedos Diet",
    "Brinquedos Combo Colorido 141",
    "Brinquedos Linha Luxo 100",
    "Brinquedos Resistente 38",
    "Anatômico para Brinquedos #112",
    "Brinquedos Ecológico 68",
    "Combo Brinquedos Reforçado",
    "Brinquedos Linha Cobre 103",
    "Brinquedos Sortido Industrial 183",
    "Brinquedos Linha Familiar 164",
    "Vidro para Brinquedos #3",
    "Tamanho Brinquedos Camurça",
    "Brinquedos - Adulto Profissional",
    "Brinquedos Sortido Camurça 179",
    "Edição Brinquedos Econômico",
    "Brinquedos Cinza 62",
    "Brinquedos Luxo 23"
  ],
  "Pet Shop": [
    "Pet Shop - Bambu Preto",
    "Bambu para Pet Shop #151",
    "Sortido Pet Shop Clássico",
    "Pet Shop Resistente 141",
    "Pet Shop - Sem Fio Solar",
    "Pet Shop - Branco Gourmet",
    "Edição Pet Shop Adulto",
    "Bambu para Pet Shop #148",
    "Pet Shop Nacional 45",
    "Nylon para Pet Shop #28",
    "Pet Shop Modelo Nylon 76",
    "Pet Shop - Maxi Veludo",
    "Pet Shop - Tricô Wi-Fi",
    "Pet Shop - Vidro Prata",
    "Pet Shop Versão Artesanal 194",
    "Pet Shop - Metal Metal",
    "Pet Shop Linha Linho 30",
    "Pet Shop - Ecológico Prata",
    "Modelo Pet Shop Orgânico",
    "Pet Shop - Madeira Preto",
    "Pet Shop Sortido Clássico 180",
    "Pet Shop - Artesanal Industrial",
    "Pet Shop Bambu 173",
    "Pet Shop - Sustentável Recarregável",
    "Estojo Pet Shop Elegante",
    "Pet Shop - Diet Wi-Fi",
    "Pet Shop - Infantil Adulto",
    "Premium Gold para Pet Shop #61",
    "Tamanho Pet Shop Nacional",
    "Pack Pet Shop Premium Gold",
    "Tamanho Pet Shop Antialérgico",
    "Pet Shop - Retro Mini",
    "Pet Shop Reforçado 174",
    "Antiderrapante para Pet Shop #2",
    "Pet Shop Linha Linho 96",
    "Pet Shop Kit Poliéster 148",
    "Pet Shop - Seda Infantil",
    "Pet Shop Edição Inox 57",
    "Pet Shop Tipo Portátil 135",
    "Linho para Pet Shop #139",
    "Pet Shop Nylon 89",
    "Familiar para Pet Shop #118",
    "Pet Shop Camurça 118",
    "Pet Shop - Clássico Clássico"
  ],
  "Ferramentas e Construção": [
    "Caixa Ferramentas e Construção Solar",
    "Ferramentas e Construção Rústico 93",
    "Ferramentas e Construção Edição Infantil 141",
    "Ferramentas e Construção - Natural Caseiro",
    "Antiderrapante para Ferramentas e Construção #88",
    "Ferramentas e Construção - Infantil Poliéster",
    "Light para Ferramentas e Construção #108",
    "Ferramentas e Construção - Cinza Bambu",
    "Ferramentas e Construção - Acrílico Infantil",
    "Ferramentas e Construção Tipo Wi-Fi 176",
    "Tamanho Ferramentas e Construção Ultra",
    "Ferramentas e Construção - Natural Sem Fio",
    "Prata para Ferramentas e Construção #51",
    "Tipo Ferramentas e Construção Retro",
    "Clássico para Ferramentas e Construção #46",
    "Poliéster para Ferramentas e Construção #35",
    "Ferramentas e Construção Sortido Elegante 125",
    "Ferramentas e Construção - Importado Sem Fio",
    "Ferramentas e Construção Linha Inox 26",
    "Kit Ferramentas e Construção Diet",
    "Ferramentas e Construção - Algodão Ultra",
    "Minimalista para Ferramentas e Construção #67",
    "Ferramentas e Construção - Cinza Sem Fio",
    "Ferramentas e Construção Edição Branco 6",
    "Slim para Ferramentas e Construção #90",
    "Ferramentas e Construção Coleção Wi-Fi 148",
    "Ferramentas e Construção Tipo Industrial 91",
    "Ferramentas e Construção - Veludo Seda",
    "Reforçado para Ferramentas e Construção #98",
    "Ferramentas e Construção Edição Couro 162",
    "Tamanho Ferramentas e Construção Econômico",
    "Ferramentas e Construção - Plástico Antiderrapante",
    "Ferramentas e Construção Combo Sustentável 21",
    "Combo Ferramentas e Construção Orgânico",
    "Ferramentas e Construção - Elegante Doméstico",
    "Ferramentas e Construção - Ergonômico Inox",
    "Ferramentas e Construção - Vidro Cinza",
    "Ferramentas e Construção Sortido Acrílico 106",
    "Linha Ferramentas e Construção Moderno",
    "Série Ferramentas e Construção Natural",
    "Ferramentas e Construção - Reforçado Light",
    "Caixa Ferramentas e Construção Mini",
    "Ferramentas e Construção Ecológico 122",
    "Ferramentas e Construção Linha Tradicional 198"
  ],
  "Materiais Elétricos": [
    "Microfibra para Materiais Elétricos #196",
    "Materiais Elétricos Mini 68",
    "Materiais Elétricos Tipo Reforçado 168",
    "Casual para Materiais Elétricos #59",
    "Série Materiais Elétricos Industrial",
    "Plus para Materiais Elétricos #34",
    "Materiais Elétricos Tipo Tradicional 9",
    "Materiais Elétricos - Rústico Algodão",
    "Crochê para Materiais Elétricos #70",
    "Materiais Elétricos Versão Eco 179",
    "Materiais Elétricos Tipo Térmico 153",
    "Bluetooth para Materiais Elétricos #112",
    "Materiais Elétricos Sortido Casual 89",
    "Crochê para Materiais Elétricos #59",
    "Materiais Elétricos Vidro 79",
    "Materiais Elétricos - Madeira Nacional",
    "Coleção Materiais Elétricos Clássico",
    "Materiais Elétricos Camurça 195",
    "Combo Materiais Elétricos Industrial",
    "Tricô para Materiais Elétricos #3",
    "Linho para Materiais Elétricos #77",
    "Materiais Elétricos Cerâmica 75",
    "Materiais Elétricos Coleção Premium 141",
    "Materiais Elétricos - Adulto Madeira",
    "Materiais Elétricos Combo Inox 64",
    "Série Materiais Elétricos Cobre",
    "Zero para Materiais Elétricos #68",
    "Materiais Elétricos Silicone 161",
    "Sortido Materiais Elétricos Antiderrapante",
    "Materiais Elétricos - Industrial Tricô",
    "Materiais Elétricos - Madeira Adulto",
    "Materiais Elétricos Infantil 35",
    "Materiais Elétricos - Maxi Metal",
    "Materiais Elétricos Versão Caseiro 180",
    "Materiais Elétricos Versão Adulto 83",
    "Materiais Elétricos Retro 13",
    "Materiais Elétricos Linha Infantil 27",
    "Materiais Elétricos - Caseiro Plus",
    "Clássico para Materiais Elétricos #60",
    "Materiais Elétricos Retro 4",
    "Diet para Materiais Elétricos #88",
    "Casual para Materiais Elétricos #128",
    "Materiais Elétricos - Couro Profissional",
    "Materiais Elétricos - Reforçado Vintage"
  ],
  "Hidráulica e Reformas": [
    "Hidráulica e Reformas Caseiro 199",
    "Sustentável para Hidráulica e Reformas #140",
    "Infantil para Hidráulica e Reformas #50",
    "Hidráulica e Reformas - Prata Clássico",
    "Hidráulica e Reformas Artesanal 99",
    "Artesanal para Hidráulica e Reformas #189",
    "Hidráulica e Reformas Premium Gold 118",
    "Hidráulica e Reformas Camurça 171",
    "Estojo Hidráulica e Reformas Cobre",
    "Hidráulica e Reformas - Rústico Luxo",
    "Hidráulica e Reformas Recarregável 134",
    "Hidráulica e Reformas Importado 124",
    "Hidráulica e Reformas - Premium Gold Cinza",
    "Hidráulica e Reformas Diet 29",
    "Modelo Hidráulica e Reformas Cerâmica",
    "Hidráulica e Reformas - Clássico Econômico",
    "Hidráulica e Reformas - Solar Slim",
    "Artesanal para Hidráulica e Reformas #3",
    "Hidráulica e Reformas Solar 177",
    "Anatômico para Hidráulica e Reformas #40",
    "Hidráulica e Reformas - Resistente Artesanal",
    "Estojo Hidráulica e Reformas Resistente",
    "Hidráulica e Reformas Kit Inteligente 16",
    "Hidráulica e Reformas - Retro Tricô",
    "Hidráulica e Reformas Plus 125",
    "Combo Hidráulica e Reformas Sem Fio",
    "Hidráulica e Reformas - Vidro Adulto",
    "Hidráulica e Reformas Prata 92",
    "Coleção Hidráulica e Reformas Compacto",
    "Vidro para Hidráulica e Reformas #144",
    "Hidráulica e Reformas - Crochê Seda",
    "Edição Hidráulica e Reformas Infantil",
    "Hidráulica e Reformas Kit Rústico 188",
    "Gourmet para Hidráulica e Reformas #154",
    "Hidráulica e Reformas Tipo Ecológico 136",
    "Estojo Hidráulica e Reformas Doméstico",
    "Hidráulica e Reformas - Crochê Cinza",
    "Premium para Hidráulica e Reformas #199",
    "Hidráulica e Reformas Combo Infantil 5",
    "Hidráulica e Reformas Kit Antialérgico 62",
    "Hidráulica e Reformas - Ecológico Tricô",
    "Adulto para Hidráulica e Reformas #135",
    "Recarregável para Hidráulica e Reformas #40",
    "Hidráulica e Reformas Edição Rústico 105"
  ],
  "Tintas e Acabamentos": [
    "Tintas e Acabamentos - Maxi Ultra",
    "Tintas e Acabamentos Modelo Compacto 34",
    "Tamanho Tintas e Acabamentos Profissional",
    "Conjunto Tintas e Acabamentos Seda",
    "Conjunto Tintas e Acabamentos Profissional",
    "Tintas e Acabamentos Combo Seda 135",
    "Tintas e Acabamentos Edição Portátil 94",
    "Edição Tintas e Acabamentos Sustentável",
    "Tintas e Acabamentos Light 168",
    "Reforçado para Tintas e Acabamentos #120",
    "Tintas e Acabamentos Cinza 143",
    "Dourado para Tintas e Acabamentos #182",
    "Tintas e Acabamentos Antiderrapante 69",
    "Tintas e Acabamentos Linha Sustentável 78",
    "Tintas e Acabamentos Diet 133",
    "Tintas e Acabamentos Ultra 186",
    "Sortido Tintas e Acabamentos Cobre",
    "Pack Tintas e Acabamentos Microfibra",
    "Edição Tintas e Acabamentos Familiar",
    "Tintas e Acabamentos Sortido Plástico 192",
    "Tintas e Acabamentos Wi-Fi 92",
    "Silicone para Tintas e Acabamentos #27",
    "Tipo Tintas e Acabamentos Infantil",
    "Tintas e Acabamentos Combo Nylon 87",
    "Sortido Tintas e Acabamentos Anatômico",
    "Preto para Tintas e Acabamentos #81",
    "Tintas e Acabamentos Kit Dourado 106",
    "Rústico para Tintas e Acabamentos #156",
    "Edição Tintas e Acabamentos Crochê",
    "Caixa Tintas e Acabamentos Recarregável",
    "Tintas e Acabamentos - Cinza Acrílico",
    "Inox para Tintas e Acabamentos #1",
    "Tintas e Acabamentos Industrial 153",
    "Tintas e Acabamentos Camurça 35",
    "Tintas e Acabamentos - Premium Esportivo",
    "Pack Tintas e Acabamentos Elegante",
    "Tintas e Acabamentos Gourmet 142",
    "Tintas e Acabamentos Sortido Wi-Fi 147",
    "Preto para Tintas e Acabamentos #40",
    "Coleção Tintas e Acabamentos Cinza",
    "Tintas e Acabamentos Coleção Orgânico 66",
    "Tintas e Acabamentos - Resistente Wi-Fi",
    "Bluetooth para Tintas e Acabamentos #56",
    "Tintas e Acabamentos Rústico 124"
  ],
  "Automotivo": [
    "Estojo Automotivo Wi-Fi",
    "Automotivo Anatômico 165",
    "Automotivo - Profissional Wi-Fi",
    "Reforçado para Automotivo #15",
    "Automotivo - Branco Cerâmica",
    "Slim para Automotivo #198",
    "Série Automotivo Ergonômico",
    "Automotivo Prata 14",
    "Automotivo - Microfibra Compacto",
    "Automotivo - Crochê Bluetooth",
    "Combo Automotivo Nylon",
    "Linha Automotivo Portátil",
    "Acrílico para Automotivo #193",
    "Automotivo Sortido Resistente 57",
    "Doméstico para Automotivo #101",
    "Linha Automotivo Colorido",
    "Automotivo Algodão 147",
    "Automotivo Recarregável 103",
    "Automotivo - Reforçado Bambu",
    "Automotivo Combo Plus 196",
    "Estojo Automotivo Sem Fio",
    "Estojo Automotivo Inox",
    "Automotivo Coleção Sem Fio 158",
    "Automotivo Coleção Artesanal 19",
    "Automotivo - Cerâmica Rústico",
    "Automotivo Modelo Maxi 172",
    "Silicone para Automotivo #94",
    "Automotivo - Adulto Rústico",
    "Automotivo - Anatômico Tradicional",
    "Automotivo - Econômico Branco",
    "Automotivo Versão Antialérgico 38",
    "Compacto para Automotivo #60",
    "Modelo Automotivo Dourado",
    "Tipo Automotivo Reforçado",
    "Automotivo Portátil 63",
    "Automotivo Tipo Industrial 4",
    "Automotivo - Maxi Casual",
    "Algodão para Automotivo #6",
    "Automotivo - Light Tricô",
    "Pack Automotivo Crochê",
    "Automotivo Edição Recarregável 124",
    "Automotivo Tipo Moderno 97",
    "Automotivo Sortido Compacto 66",
    "Kit Automotivo Industrial"
  ],
  "Motopeças": [
    "Tipo Motopeças Antialérgico",
    "Motopeças - Portátil Couro",
    "Motopeças Ecológico 100",
    "Motopeças - Cinza Mini",
    "Motopeças Doméstico 167",
    "Orgânico para Motopeças #98",
    "Motopeças Modelo Elegante 125",
    "Motopeças Sortido Resistente 48",
    "Sortido Motopeças Metal",
    "Motopeças Linha Compacto 64",
    "Motopeças Edição Minimalista 126",
    "Luxo para Motopeças #5",
    "Motopeças - Preto Preto",
    "Motopeças - Natural Nylon",
    "Motopeças - Inteligente Importado",
    "Tradicional para Motopeças #143",
    "Motopeças - Zero Retro",
    "Motopeças - Inox Eco",
    "Motopeças Prata 134",
    "Motopeças Coleção Plástico 62",
    "Motopeças Tipo Silicone 80",
    "Motopeças Kit Acrílico 139",
    "Pack Motopeças Eco",
    "Motopeças Sortido Premium Gold 36",
    "Motopeças - Microfibra Eco",
    "Vintage para Motopeças #168",
    "Motopeças Tipo Elegante 18",
    "Motopeças Sortido Slim 48",
    "Motopeças - Vintage Tradicional",
    "Motopeças - Madeira Madeira",
    "Motopeças - Vidro Gourmet",
    "Tipo Motopeças Adulto",
    "Motopeças Plus 48",
    "Motopeças Antiderrapante 158",
    "Motopeças - Ergonômico Bluetooth",
    "Motopeças Coleção Anatômico 60",
    "Modelo Motopeças Tradicional",
    "Motopeças - Reforçado Linho",
    "Sortido Motopeças Ergonômico",
    "Dourado para Motopeças #48",
    "Seda para Motopeças #122",
    "Linha Motopeças Adulto",
    "Kit Motopeças Madeira",
    "Motopeças Caseiro 106"
  ],
  "Papelaria e Escritório": [
    "Série Papelaria e Escritório Premium Gold",
    "Conjunto Papelaria e Escritório Familiar",
    "Antiderrapante para Papelaria e Escritório #126",
    "Papelaria e Escritório - Metal Artesanal",
    "Bambu para Papelaria e Escritório #199",
    "Papelaria e Escritório Ergonômico 189",
    "Elegante para Papelaria e Escritório #101",
    "Papelaria e Escritório Sortido Microfibra 165",
    "Papelaria e Escritório Camurça 28",
    "Metal para Papelaria e Escritório #11",
    "Sortido Papelaria e Escritório Tricô",
    "Compacto para Papelaria e Escritório #143",
    "Camurça para Papelaria e Escritório #196",
    "Papelaria e Escritório Adulto 75",
    "Inox para Papelaria e Escritório #78",
    "Papelaria e Escritório - Couro Econômico",
    "Doméstico para Papelaria e Escritório #157",
    "Papelaria e Escritório Camurça 37",
    "Acrílico para Papelaria e Escritório #24",
    "Papelaria e Escritório Modelo Infantil 150",
    "Papelaria e Escritório Tipo Inox 106",
    "Papelaria e Escritório - Acrílico Tradicional",
    "Estojo Papelaria e Escritório Térmico",
    "Versão Papelaria e Escritório Metal",
    "Papelaria e Escritório Importado 83",
    "Série Papelaria e Escritório Slim",
    "Papelaria e Escritório Maxi 181",
    "Cinza para Papelaria e Escritório #22",
    "Papelaria e Escritório Combo Veludo 157",
    "Caixa Papelaria e Escritório Recarregável",
    "Compacto para Papelaria e Escritório #197",
    "Versão Papelaria e Escritório Minimalista",
    "Papelaria e Escritório Tipo Luxo 38",
    "Tipo Papelaria e Escritório Portátil",
    "Casual para Papelaria e Escritório #80",
    "Industrial para Papelaria e Escritório #161",
    "Conjunto Papelaria e Escritório Plus",
    "Kit Papelaria e Escritório Antialérgico",
    "Papelaria e Escritório - Clássico Metal",
    "Poliéster para Papelaria e Escritório #140",
    "Papelaria e Escritório Ergonômico 127",
    "Pack Papelaria e Escritório Térmico",
    "Metal para Papelaria e Escritório #105",
    "Reforçado para Papelaria e Escritório #154"
  ],
  "Livros e Hobbies": [
    "Livros e Hobbies Linha Artesanal 141",
    "Livros e Hobbies - Antialérgico Sem Fio",
    "Kit Livros e Hobbies Infantil",
    "Kit Livros e Hobbies Branco",
    "Livros e Hobbies Vintage 9",
    "Livros e Hobbies Edição Minimalista 23",
    "Livros e Hobbies Mini 107",
    "Linha Livros e Hobbies Industrial",
    "Livros e Hobbies Sortido Familiar 117",
    "Livros e Hobbies Kit Profissional 24",
    "Livros e Hobbies - Rústico Dourado",
    "Ecológico para Livros e Hobbies #195",
    "Recarregável para Livros e Hobbies #17",
    "Livros e Hobbies - Algodão Eco",
    "Livros e Hobbies Gourmet 85",
    "Livros e Hobbies Combo Microfibra 54",
    "Edição Livros e Hobbies Inteligente",
    "Livros e Hobbies Wi-Fi 187",
    "Livros e Hobbies Modelo Linho 186",
    "Livros e Hobbies Edição Silicone 156",
    "Livros e Hobbies - Nacional Microfibra",
    "Livros e Hobbies Kit Plus 158",
    "Livros e Hobbies Versão Camurça 187",
    "Poliéster para Livros e Hobbies #47",
    "Livros e Hobbies Coleção Doméstico 50",
    "Livros e Hobbies Slim 7",
    "Slim para Livros e Hobbies #189",
    "Tipo Livros e Hobbies Antiderrapante",
    "Madeira para Livros e Hobbies #12",
    "Livros e Hobbies - Branco Sem Fio",
    "Kit Livros e Hobbies Premium Gold",
    "Livros e Hobbies - Importado Ecológico",
    "Livros e Hobbies - Esportivo Nylon",
    "Livros e Hobbies Kit Premium 30",
    "Livros e Hobbies - Colorido Inox",
    "Livros e Hobbies Linha Familiar 50",
    "Livros e Hobbies - Colorido Linho",
    "Profissional para Livros e Hobbies #166",
    "Estojo Livros e Hobbies Retro",
    "Tricô para Livros e Hobbies #86",
    "Madeira para Livros e Hobbies #191",
    "Livros e Hobbies Camurça 77",
    "Livros e Hobbies Kit Sem Fio 138",
    "Livros e Hobbies Light 148"
  ],
  "Instrumentos Musicais": [
    "Instrumentos Musicais - Preto Ecológico",
    "Coleção Instrumentos Musicais Tradicional",
    "Instrumentos Musicais - Prata Tricô",
    "Edição Instrumentos Musicais Ergonômico",
    "Infantil para Instrumentos Musicais #153",
    "Instrumentos Musicais Casual 181",
    "Instrumentos Musicais - Profissional Caseiro",
    "Resistente para Instrumentos Musicais #128",
    "Combo Instrumentos Musicais Acrílico",
    "Instrumentos Musicais - Diet Microfibra",
    "Instrumentos Musicais - Familiar Maxi",
    "Instrumentos Musicais - Profissional Premium Gold",
    "Instrumentos Musicais Vidro 130",
    "Instrumentos Musicais Linho 129",
    "Pack Instrumentos Musicais Colorido",
    "Microfibra para Instrumentos Musicais #80",
    "Instrumentos Musicais - Vintage Ultra",
    "Instrumentos Musicais Tipo Light 186",
    "Instrumentos Musicais Metal 100",
    "Instrumentos Musicais Modelo Premium 80",
    "Instrumentos Musicais Anatômico 23",
    "Instrumentos Musicais - Couro Compacto",
    "Instrumentos Musicais Camurça 197",
    "Instrumentos Musicais - Moderno Wi-Fi",
    "Instrumentos Musicais - Light Rústico",
    "Pack Instrumentos Musicais Industrial",
    "Instrumentos Musicais - Tricô Elegante",
    "Slim para Instrumentos Musicais #70",
    "Linha Instrumentos Musicais Gourmet",
    "Instrumentos Musicais Clássico 160",
    "Instrumentos Musicais Sortido Mini 53",
    "Instrumentos Musicais Kit Recarregável 82",
    "Instrumentos Musicais - Vintage Industrial",
    "Instrumentos Musicais Coleção Econômico 19",
    "Instrumentos Musicais - Antiderrapante Colorido",
    "Instrumentos Musicais Versão Portátil 34",
    "Instrumentos Musicais Algodão 173",
    "Instrumentos Musicais Mini 99",
    "Instrumentos Musicais Resistente 110",
    "Familiar para Instrumentos Musicais #181",
    "Instrumentos Musicais Versão Antiderrapante 92",
    "Instrumentos Musicais - Minimalista Premium Gold",
    "Instrumentos Musicais Modelo Couro 146",
    "Conjunto Instrumentos Musicais Couro"
  ]
};

export const ALL_CATEGORIES = Object.keys(CATEGORIES_TREE);
