GRANT USAGE ON SCHEMA auth TO sandbox_exec;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA auth TO sandbox_exec;
GRANT REFERENCES ON ALL TABLES IN SCHEMA auth TO sandbox_exec;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO sandbox_exec;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA auth TO sandbox_exec;